// ============================================================
// FROSTBITE STATION — game-logic.js
// Generated by Hex Corbin (gameplay-coder)
// Data-driven adventure engine for 008-frostbite-station
// ============================================================

const GAME_DATA = {
  "title": "Frostbite Station",
  "slug": "frostbite-station",
  "number": 8,
  "setting": "An abandoned Arctic research station built over a frozen lake. The crew discovered something ancient in the ice that thawed out and now moves in the darkness.",
  "characters": [
    {
      "id": "dr-okafor",
      "name": "Dr. Elara Okafor",
      "description": "Lead researcher of Frostbite Station. Her research journal suggests she uncovered something terrifying in the ice core samples."
    },
    {
      "id": "watcher-ice",
      "name": "The Watcher in the Ice",
      "description": "An ancient entity frozen for millennia, now thawed and stalking the station's corridors. It moves silently, leaving frost patterns and cold spots."
    }
  ],
  "items": [
    {
      "id": "flare-torch",
      "name": "Flare Torch",
      "description": "A red emergency flare with a striker wheel. Produces intense heat that can thaw frozen mechanisms.",
      "foundIn": "landing-pad",
      "usedIn": "landing-pad",
      "usedOn": "puzzle-thaw-door"
    },
    {
      "id": "keycard-maintenance",
      "name": "Maintenance Keycard (MAINT-04)",
      "description": "An amber-glowing keycard with frost-damaged edges. Security clearance for maintenance areas.",
      "foundIn": "main-corridor",
      "usedIn": "main-corridor",
      "usedOn": "puzzle-unlock-lab"
    },
    {
      "id": "sample-drill",
      "name": "Sample Drill",
      "description": "A heavy-duty coring drill with diamond-tipped bit. Used for extracting ice samples from permafrost.",
      "foundIn": "laboratory",
      "usedIn": "laboratory",
      "usedOn": "puzzle-extract-core"
    },
    {
      "id": "ice-core-artifact",
      "name": "Ice Core Artifact",
      "description": "A cylindrical ice sample containing a dark, organic-looking mass frozen within. Feels unnaturally cold to the touch.",
      "foundIn": "laboratory",
      "usedIn": "frozen-chamber",
      "usedOn": "puzzle-win"
    },
    {
      "id": "research-journal",
      "name": "Dr. Okafor's Research Journal",
      "description": "A leather-bound journal with frantic handwriting. Contains frequency codes (7.83 Hz, 14.3 Hz) and notes about 'resonance patterns' and 'awakening something'.",
      "foundIn": "laboratory",
      "usedIn": "generator-room",
      "usedOn": "puzzle-power-generator"
    },
    {
      "id": "frequency-transmitter",
      "name": "Frequency Transmitter",
      "description": "A portable device that can broadcast specific low-frequency signals. Used for geological resonance experiments.",
      "foundIn": "comm-room",
      "usedIn": "generator-room",
      "usedOn": "puzzle-power-generator"
    },
    {
      "id": "emergency-fuse",
      "name": "Emergency Fuse",
      "description": "A heavy ceramic fuse rated for high-voltage systems. Found in the lab's spare parts cabinet.",
      "foundIn": "laboratory",
      "usedIn": "generator-room",
      "usedOn": "puzzle-power-generator"
    }
  ],
  "scenes": [
    {
      "id": "landing-pad",
      "name": "Landing Pad",
      "prose": "The wind howls across the frozen landing pad, biting through your thermal gear with needles of ice. Frostbite Station looms before you\u2014a cluster of brutalist concrete structures half-buried in snowdrifts, their windows dark and vacant. The main entrance is a steel blast door sealed shut, ice glazing its edges like a frosted tomb. To the north, the corridor entrance waits behind a layer of thick, milky ice that has swollen in the frame. Crates lie overturned, their contents spilled and frozen solid: rations, tools, a scattering of personal effects abandoned in haste. Wedged between two crates, a red cylinder catches your eye\u2014a flare torch, its striker wheel crusted with rime but still functional. The wind carries a sound that isn't wind: a low, resonant hum, felt more than heard, vibrating up through the packed snow under your boots. The station isn't empty. Something is awake inside.",
      "exits": {
        "north": "main-corridor"
      },
      "items": ["flare-torch"],
      "puzzles": ["puzzle-thaw-door"],
      "lookDescriptions": {
        "flare-torch": "A red emergency flare with a metal striker wheel. The label reads 'EXTREME HEAT - USE FOR ICE EMERGENCIES'.",
        "crates": "Overturned supply crates, contents frozen into indistinguishable lumps. One crate lid is smashed, revealing mangled equipment inside.",
        "blast-door": "The main station entrance, sealed with thick ice around the edges. No visible handles or controls\u2014likely opened from inside.",
        "snowdrifts": "Deep, wind-sculpted snow piles against the station walls. Strange, swirling patterns are etched into their surfaces, as if something has moved through them without leaving footprints.",
        "frozen-door": "The corridor entrance, blocked by a thick wall of milky ice. The ice has swollen in the frame, sealing it shut."
      }
    },
    {
      "id": "main-corridor",
      "name": "Main Corridor",
      "prose": "Dim red emergency lighting casts long shadows down the corridor, painting everything in the color of old blood. Frost webs across the walls, thick and crystalline, catching the light like frozen capillaries. Three doors branch off: to the west, a door labeled COMM ROOM hangs slightly ajar, darkness pooling beyond; to the east, a sealed door marked LAB glows with the amber light of a card reader, locked; ahead, a heavy reinforced door labeled GENERATOR ROOM vibrates with a low, mechanical pulse. The air is dead-cold and still, smelling of ozone and something organic, like wet soil and decay. A locker has toppled over, spilling jackets and tools. Near it, an amber-glowing keycard lies on the frost-rimed floor\u2014MAINTENANCE-04, dropped in someone's flight. The red light makes the frost patterns on the walls seem to writhe if you stare too long.",
      "exits": {
        "south": "landing-pad",
        "west": "comm-room",
        "east": "laboratory",
        "north": "generator-room"
      },
      "items": ["keycard-maintenance"],
      "puzzles": ["puzzle-unlock-lab"],
      "lookDescriptions": {
        "keycard-maintenance": "An amber keycard labeled MAINT-04. Frost has crept into its chip slot, but the LED still glows weakly.",
        "locker": "A fallen metal locker, contents spilled: thermal jackets, a broken flashlight, a half-frozen coffee mug.",
        "frost-patterns": "Intricate, fern-like frost crystals covering the walls. They seem to grow thicker near the generator room door.",
        "card-reader": "The lab door's electronic lock. Amber light pulses slowly, waiting for a valid keycard.",
        "lab-door": "A sealed door marked LAB, its card reader glowing amber. Locked."
      }
    },
    {
      "id": "comm-room",
      "name": "Communications Room",
      "prose": "Banks of dead radio equipment line the walls, their screens dark and dusty. A central console dominates the room, its surface littered with papers\u2014frequency charts, call logs, a handwritten note in a desperate, sprawling script: 'DON'T TRANSMIT BELOW 10 Hz\u2014IT HEARS.' The chair is pushed back as if someone stood up quickly, a thermal mug knocked over, its contents frozen in a brown spill across the floor. On a smaller side table sits a portable frequency transmitter, its display still lit with a soft green glow, showing a standby frequency of 1.00 Hz. A large world map on the wall is dotted with pins marking other research stations, all in the Arctic circle. One pin, red and larger than the rest, marks Frostbite Station. Someone has drawn a circle around it in black marker, and written a single word: 'GROUND ZERO.'",
      "exits": {
        "east": "main-corridor"
      },
      "items": ["frequency-transmitter"],
      "puzzles": [],
      "lookDescriptions": {
        "frequency-transmitter": "A portable device with a digital display and tuning dials. Label: 'RESONANCE EMITTER - GEO-ACOUSTIC STUDIES'.",
        "console": "The main communications console. Power is off, but a spare battery pack still has charge.",
        "note": "A handwritten note: 'DON'T TRANSMIT BELOW 10 Hz\u2014IT HEARS. Okafor ordered full silence. Too late now.'",
        "world-map": "A map of the Arctic with research stations marked. Frostbite Station is circled in black with 'GROUND ZERO' scrawled beside it."
      }
    },
    {
      "id": "laboratory",
      "name": "Laboratory",
      "prose": "The lab is a disaster of shattered glass and overturned equipment. Sample jars lie broken on the floor, their contents\u2014ice cores, geological specimens\u2014scattered and melting into foul-smelling puddles. In the center of the room, a massive permafrost-sampling rig stands intact, its drill bit pointed at a section of exposed bedrock wall. The wall shows clear drill marks, and at its center, a cylindrical borehole glistens with fresh ice. On a workbench, a heavy sample drill rests beside a spilled toolbox. A cabinet labeled 'SPARE PARTS' hangs open; inside, among fuses and wiring, you spot a ceramic emergency fuse. Cold radiates from the borehole in waves, and the air tastes metallic, like blood and ozone. Frost creeps across the floor in intricate, spiral patterns, converging on the drill site.",
      "exits": {
        "west": "main-corridor"
      },
      "items": ["sample-drill", "emergency-fuse"],
      "puzzles": ["puzzle-extract-core"],
      "lookDescriptions": {
        "sample-drill": "A heavy coring drill with a diamond-tipped bit. The motor is cold but seems operational.",
        "permafrost-wall": "A section of exposed bedrock with a fresh borehole. Ice glints deep within the hole, something dark suspended inside.",
        "spare-parts-cabinet": "An open cabinet containing electrical components. The emergency fuse is the largest, rated for 10kV.",
        "broken-samples": "Shattered ice-core jars. The melting ice smells wrong\u2014sweet and rotten, like decayed fruit.",
        "borehole": "A cylindrical hole drilled into the permafrost wall. Something dark is frozen inside the ice deep within."
      }
    },
    {
      "id": "generator-room",
      "name": "Generator Room",
      "prose": "The generator room thrums with latent power. A massive diesel generator occupies the center, its casing frosted over but still emitting a deep, sub-sonic vibration that shakes the floor. Control panels line the walls, their gauges frozen at zero. One panel has been ripped open, exposing burnt wiring and a missing fuse socket. To the south, a heavy vault door stands sealed, its surface etched with the same swirling frost patterns seen elsewhere, but here they form something almost glyph-like. A workbench holds tools and a frequency-coupling unit\u2014a device clearly meant to interface the transmitter with the generator. The air is thick with the smell of diesel and ozone, and the vibration gets into your bones, making your teeth ache. The vault door has no handle, only a small, frosted-over viewport that shows darkness beyond.",
      "exits": {
        "south": "frozen-chamber",
        "west": "main-corridor"
      },
      "items": [],
      "puzzles": ["puzzle-power-generator"],
      "lookDescriptions": {
        "generator": "A massive diesel generator, frosted over but still producing a low vibration. The missing fuse socket is clearly visible.",
        "vault-door": "A heavy circular door with frost-etched glyphs. The viewport is clouded with ice, but something dark moves beyond.",
        "frequency-coupler": "A rack-mounted unit with input ports for a transmitter and output leads to the generator.",
        "control-panels": "Frost-covered gauges and switches. One panel is smashed, wires hanging out like black intestines."
      }
    },
    {
      "id": "frozen-chamber",
      "name": "Frozen Chamber",
      "prose": "The vault door opens onto a vast, natural cavern, its walls sheathed in blue-white ice that glows with an internal phosphorescence. In the center of the chamber, an ancient device of black stone and frozen metal rises from the ice\u2014a machine of impossible geometry, all sharp angles and non-Euclidean curves. Before it, a pedestal holds a recessed slot exactly the size of the ice-core artifact. The air is deathly still and so cold it burns your lungs. The ice walls are not empty: shadows move within them, elongated humanoid shapes frozen mid-stride, faces pressed against the ice as if trying to break through. The Watcher is here\u2014a presence felt rather than seen, a pressure in the air, a whispering at the edge of hearing. The device hums, awaiting the final key. This is where it all ends, or begins.",
      "exits": {
        "north": "generator-room"
      },
      "items": [],
      "puzzles": ["puzzle-win"],
      "lookDescriptions": {
        "ancient-device": "A structure of black stone and frozen metal, covered in glyphs that swim when you look away. A pedestal before it has a cylindrical slot.",
        "ice-walls": "Glowing blue ice containing frozen shadows\u2014humanoid shapes trapped forever, their faces distorted in silent screams.",
        "pedestal": "A stone pedestal with a slot exactly matching the ice-core artifact. Glyphs around it pulse with faint light.",
        "cavern": "A vast natural chamber, the ceiling lost in darkness. The ice underfoot is treacherously smooth, and the cold is absolute."
      }
    }
  ],
  "puzzles": [
    {
      "id": "puzzle-thaw-door",
      "scene": "landing-pad",
      "requires": ["flare-torch"],
      "action": "use flare-torch on frozen-door",
      "result": "The flare ignites with a hissing roar, pouring intense heat onto the ice-sealed door. The ice melts rapidly, steaming away to reveal the corridor entrance. The door groans open, releasing a gust of frigid, stale air.",
      "reveals": [],
      "blocksExit": {
        "scene": "landing-pad",
        "direction": "north",
        "blockedMessage": "The corridor entrance is sealed shut by a thick wall of ice. You need something to melt it."
      }
    },
    {
      "id": "puzzle-unlock-lab",
      "scene": "main-corridor",
      "requires": ["keycard-maintenance"],
      "action": "use keycard-maintenance on lab-door",
      "result": "The keycard clicks home. The amber light flashes green, and the lab door slides open with a whisper of compressed air. Cold, metallic-scented air washes out from the darkness within.",
      "reveals": [],
      "blocksExit": {
        "scene": "main-corridor",
        "direction": "east",
        "blockedMessage": "The lab door is locked. Its card reader pulses amber, waiting for a valid keycard."
      }
    },
    {
      "id": "puzzle-extract-core",
      "scene": "laboratory",
      "requires": ["sample-drill"],
      "action": "use sample-drill on permafrost-wall",
      "result": "The drill whines to life, biting into the ice-filled borehole. With a crack, the core breaks free\u2014a cylinder of clear ice containing a dark, organic mass. As you lift it, a leather-bound journal, frozen inside the ice, falls to the floor. You now have the ice-core artifact and Dr. Okafor's research journal.",
      "reveals": ["ice-core-artifact", "research-journal"],
      "blocksExit": null
    },
    {
      "id": "puzzle-power-generator",
      "scene": "generator-room",
      "requires": ["emergency-fuse", "frequency-transmitter", "research-journal"],
      "action": "install fuse and tune transmitter to 7.83 Hz",
      "result": "The fuse slots into the generator with a heavy click. The transmitter, tuned to the frequency from the journal, feeds a low hum into the coupling unit. Lights flicker on across the control panels, and the vault door's frost patterns glow with blue light before sliding open with a deep rumble.",
      "reveals": [],
      "blocksExit": {
        "scene": "generator-room",
        "direction": "south",
        "blockedMessage": "The vault door is sealed shut, its frost-etched glyphs pulsing faintly. The generator needs power to open it."
      }
    },
    {
      "id": "puzzle-win",
      "scene": "frozen-chamber",
      "requires": ["ice-core-artifact", "frequency-transmitter"],
      "action": "place ice-core artifact in pedestal and activate transmitter",
      "result": "The artifact slots perfectly into the pedestal. The transmitter, still tuned to the resonance frequency, activates the ancient device. The black stone structure awakens, glyphs burning with cold blue fire. The Watcher's presence intensifies, then dissolves into a sigh of escaping cold. The device falls silent, the threat contained\u2014for now. You have survived Frostbite Station.",
      "reveals": [],
      "blocksExit": null
    }
  ],
  "hints": {
    "landing-pad": [
      { "delay": 30, "text": "That flare torch produces serious heat. Might thaw something frozen." },
      { "delay": 60, "text": "USE the flare torch on the frozen door to the north." },
      { "delay": 90, "text": "Heat the frozen door north. Then go through." }
    ],
    "main-corridor": [
      { "delay": 30, "text": "The lab door is locked. That keycard might help." },
      { "delay": 60, "text": "USE keycard on the lab door east." },
      { "delay": 90, "text": "Swipe the keycard at the card reader. East door opens." }
    ],
    "comm-room": [
      { "delay": 30, "text": "The frequency transmitter could be useful in the generator room." },
      { "delay": 60, "text": "Take the frequency transmitter, go east to main corridor." },
      { "delay": 90, "text": "Grab the transmitter. Head to generator room." }
    ],
    "laboratory": [
      { "delay": 30, "text": "The permafrost wall has something inside. The sample drill might extract it." },
      { "delay": 60, "text": "USE sample drill on the permafrost-wall. Also grab the emergency fuse from the cabinet." },
      { "delay": 90, "text": "Drill the wall, get the core. Take the fuse too." }
    ],
    "generator-room": [
      { "delay": 30, "text": "The generator needs a fuse, the transmitter, and the journal to power the vault." },
      { "delay": 60, "text": "Install the emergency fuse, use the frequency transmitter and journal on the generator." },
      { "delay": 90, "text": "Insert fuse, tune transmitter to 7.83 Hz (from journal), activate. Vault opens south." }
    ],
    "frozen-chamber": [
      { "delay": 30, "text": "The pedestal and transmitter can seal the Watcher. Do you have both?" },
      { "delay": 60, "text": "USE ice-core artifact on pedestal, then activate transmitter." },
      { "delay": 90, "text": "Place the artifact in the slot, broadcast the frequency. Watcher contained." }
    ]
  },
  "winCondition": {
    "scene": "frozen-chamber",
    "requires": ["ice-core-artifact", "frequency-transmitter"],
    "description": "Place the ice-core artifact into the pedestal and activate the frequency transmitter to resonate with the ancient device, sealing the Watcher back into the ice."
  }
};

// ---- Game State ----
const state = {
  currentScene: 'landing-pad',
  inventory: [],
  solvedPuzzles: [],
  visitedScenes: ['landing-pad'],
  activeCommand: null,
  selectedItem: null,
  won: false,
  hintsEnabled: true,
  hintTimer: null,
  hintIndex: 0
};

// ---- DOM References ----
const artDisplay = document.getElementById('art-display');
const sceneName = document.getElementById('scene-name');
const textDisplay = document.getElementById('text-display');
const invBar = document.getElementById('inventory-bar');
const exitsBar = document.getElementById('exits-bar');

// ---- Display Functions ----
function addText(text, cls = '') {
  const p = document.createElement('p');
  p.className = cls;
  p.innerHTML = text;
  textDisplay.appendChild(p);
  textDisplay.scrollTop = textDisplay.scrollHeight;
}

function clearText() { textDisplay.innerHTML = ''; }

// ---- Locked Exit Check ----
function canExit(sceneId, direction) {
  const scene = GAME_DATA.scenes.find(s => s.id === sceneId);
  if (!scene || !scene.exits || !scene.exits[direction]) return false;

  // Check if any unsolved puzzle blocks this exit
  const blocker = GAME_DATA.puzzles.find(p =>
    p.blocksExit &&
    p.blocksExit.scene === sceneId &&
    p.blocksExit.direction === direction &&
    !state.solvedPuzzles.includes(p.id)
  );

  if (blocker) {
    addText('[The way ' + direction + ' is blocked. ' + (blocker.blocksExit.blockedMessage || 'Something prevents you from going that way.') + ']', 'locked');
    return false;
  }

  return true;
}

// ---- Visual State Changes ----
function flashPuzzleSolved() {
  if (artDisplay) {
    artDisplay.classList.add('puzzle-solved');
    setTimeout(() => artDisplay.classList.remove('puzzle-solved'), 600);
  }
}

function highlightNewlyUnlocked() {
  // Mark exit buttons that were just unlocked
  setTimeout(() => {
    document.querySelectorAll('.exit-btn').forEach(btn => {
      if (btn.classList.contains('available')) {
        btn.classList.add('newly-unlocked');
        setTimeout(() => btn.classList.remove('newly-unlocked'), 3000);
      }
    });
  }, 100);
}

function highlightNewItem(itemId) {
  setTimeout(() => {
    document.querySelectorAll('.inv-item').forEach(el => {
      if (el.dataset.item === itemId) {
        el.classList.add('item-new');
        setTimeout(() => el.classList.remove('item-new'), 2000);
      }
    });
  }, 100);
}

// ---- Hint System ----
function clearHintTimer() {
  if (state.hintTimer) { clearTimeout(state.hintTimer); state.hintTimer = null; }
  state.hintIndex = 0;
}

function startHintTimer(sceneId) {
  clearHintTimer();
  if (!state.hintsEnabled || !GAME_DATA.hints || !GAME_DATA.hints[sceneId]) return;
  const hints = GAME_DATA.hints[sceneId];
  if (!hints.length) return;
  state.hintTimer = setTimeout(() => showHint(sceneId, 0), hints[0].delay * 1000);
}

function showHint(sceneId, index) {
  if (!state.hintsEnabled || !GAME_DATA.hints || !GAME_DATA.hints[sceneId]) return;
  const hints = GAME_DATA.hints[sceneId];
  if (index >= hints.length) return;
  const hint = hints[index];
  addText(`🤔 HINT: ${hint.text}`, 'hint');
  state.hintIndex = index + 1;
  if (state.hintIndex < hints.length) {
    state.hintTimer = setTimeout(() => showHint(sceneId, state.hintIndex), hints[state.hintIndex].delay * 1000);
  }
}

// ---- Scene Rendering ----
function renderScene(sceneId) {
  const scene = GAME_DATA.scenes.find(s => s.id === sceneId);
  if (!scene) { addText('ERROR: Scene not found!', 'error'); return; }

  clearHintTimer();
  state.currentScene = sceneId;
  if (!state.visitedScenes.includes(sceneId)) state.visitedScenes.push(sceneId);

  // Update scene name
  sceneName.textContent = scene.name.toUpperCase();

  // Update art
  const artKey = 'scene-' + sceneId.replace('scene-', '');
  if (window.GAME_ART && window.GAME_ART[artKey]) {
    artDisplay.innerHTML = window.GAME_ART[artKey];
  } else {
    artDisplay.innerHTML = '<span class="no-art">[ ' + scene.name.toUpperCase() + ' ]</span>';
  }

  // Display prose
  clearText();
  addText(scene.prose);

  // Show available items (not yet taken)
  const availableItems = (scene.items || []).filter(itemId =>
    !state.inventory.includes(itemId)
  );
  if (availableItems.length > 0) {
    const itemNames = availableItems.map(id => {
      const item = GAME_DATA.items.find(i => i.id === id);
      return item ? '<span class="look-target" data-look="' + id + '">' + item.name + '</span>' : id;
    });
    addText('You notice: ' + itemNames.join(', '), 'system');
  }

  // Show unsolved puzzles
  const scenePuzzles = (scene.puzzles || []).filter(pid =>
    !state.solvedPuzzles.includes(pid)
  );
  scenePuzzles.forEach(pid => {
    const puzzle = GAME_DATA.puzzles.find(p => p.id === pid);
    if (puzzle) {
      // Don't show hint text for puzzle scenes that just need items used
    }
  });

  // Render exits
  renderExits(scene.exits || {});

  // Render inventory
  renderInventory();

  // Check win condition
  checkWin();

  // Start hint timer
  startHintTimer(sceneId);

  // Save state
  saveState();
}

function renderExits(exits) {
  exitsBar.innerHTML = '';
  const directions = ['north', 'south', 'east', 'west'];
  directions.forEach(dir => {
    const targetSceneId = exits[dir];
    if (!targetSceneId) return; // Don't show non-existent exits

    const btn = document.createElement('button');
    btn.className = 'exit-btn';

    // Check if this exit is blocked by an unsolved puzzle
    const blocker = GAME_DATA.puzzles.find(p =>
      p.blocksExit &&
      p.blocksExit.scene === state.currentScene &&
      p.blocksExit.direction === dir &&
      !state.solvedPuzzles.includes(p.id)
    );

    if (blocker) {
      // Exit exists but is locked
      btn.textContent = dir.toUpperCase() + ' [LOCKED]';
      btn.style.borderColor = '#666';
      btn.style.color = '#666';
      btn.onclick = () => canExit(state.currentScene, dir); // Will show blocked message
    } else {
      btn.textContent = dir.toUpperCase();
      btn.classList.add('available');
      btn.onclick = () => go(targetSceneId);
    }

    exitsBar.appendChild(btn);
  });
}

function renderInventory() {
  const items = invBar.querySelectorAll('.inv-item');
  items.forEach(el => el.remove());
  const empty = document.getElementById('inv-empty');

  if (state.inventory.length === 0) {
    if (empty) empty.style.display = '';
  } else {
    if (empty) empty.style.display = 'none';
    state.inventory.forEach(itemId => {
      const item = GAME_DATA.items.find(i => i.id === itemId);
      if (!item) return;
      const el = document.createElement('span');
      el.className = 'inv-item' + (state.selectedItem === itemId ? ' selected' : '');
      el.dataset.item = itemId;
      el.textContent = item.name;
      el.onclick = () => selectItem(itemId);
      invBar.appendChild(el);
    });
  }
}

// ---- Command Handlers ----
function setCommand(cmd) {
  state.activeCommand = cmd;
  document.querySelectorAll('.cmd-btn').forEach(b => {
    b.classList.toggle('active', b.dataset.cmd === cmd);
  });

  if (cmd === 'look') {
    const scene = GAME_DATA.scenes.find(s => s.id === state.currentScene);
    if (scene && scene.lookDescriptions) {
      const targets = Object.keys(scene.lookDescriptions);
      if (targets.length > 0) {
        addText('You can examine: ' + targets.map(t =>
          '<span class="look-target" data-look="' + t + '">' + t + '</span>'
        ).join(', '), 'system');
      }
    }
  } else if (cmd === 'use') {
    if (state.inventory.length > 0) {
      addText('Select an item from your inventory, then click what to use it on.', 'system');
    } else {
      addText('You have nothing to use.', 'system');
    }
  } else if (cmd === 'take') {
    const scene = GAME_DATA.scenes.find(s => s.id === state.currentScene);
    const available = (scene.items || []).filter(id => !state.inventory.includes(id));
    if (available.length > 0) {
      available.forEach(id => takeItem(id));
    } else {
      addText('Nothing here to take.', 'system');
    }
  }
}

function selectItem(itemId) {
  state.selectedItem = state.selectedItem === itemId ? null : itemId;
  renderInventory();
  if (state.selectedItem) {
    const item = GAME_DATA.items.find(i => i.id === itemId);
    addText('Selected: ' + item.name + '. Click USE, then a target.', 'system');
  }
}

function takeItem(itemId) {
  if (state.inventory.includes(itemId)) return;
  const item = GAME_DATA.items.find(i => i.id === itemId);
  if (!item) return;
  const scene = GAME_DATA.scenes.find(s => s.id === state.currentScene);
  if (!scene || !(scene.items || []).includes(itemId)) return;

  state.inventory.push(itemId);
  addText('You picked up: ' + item.name + ' \u2014 ' + item.description, 'success');
  renderInventory();
  saveState();
}

function lookAt(target) {
  const scene = GAME_DATA.scenes.find(s => s.id === state.currentScene);
  if (scene && scene.lookDescriptions && scene.lookDescriptions[target]) {
    addText(scene.lookDescriptions[target]);
  } else {
    // Check if it's an item
    const item = GAME_DATA.items.find(i => i.id === target);
    if (item) {
      addText(item.description);
    } else {
      addText('Nothing interesting about that.', 'system');
    }
  }
}

function useItemOn(itemId, targetId) {
  // Check for puzzle matching
  const puzzle = GAME_DATA.puzzles.find(p =>
    p.scene === state.currentScene &&
    !state.solvedPuzzles.includes(p.id)
  );

  if (!puzzle) {
    addText("That doesn't work here.", 'system');
    return;
  }

  // For multi-item puzzles, we need all required items
  const allItemsRequired = puzzle.requires.every(req => state.inventory.includes(req));

  // Check if this specific item is part of this puzzle and we're using on correct target
  const isCorrectItem = puzzle.requires.includes(itemId);
  const isCorrectTarget = (puzzle.id === targetId) ||
    (targetId === puzzle.scene) ||
    (puzzle.action && puzzle.action.includes(targetId));

  if (isCorrectItem && allItemsRequired) {
    solvePuzzle(puzzle);
  } else if (!isCorrectItem) {
    addText("That item doesn't seem useful here.", 'system');
  } else if (!allItemsRequired) {
    const missing = puzzle.requires.filter(req => !state.inventory.includes(req));
    const missingNames = missing.map(id => {
      const item = GAME_DATA.items.find(i => i.id === id);
      return item ? item.name : id;
    });
    addText("You don't have everything you need. Missing: " + missingNames.join(', '), 'system');
  }
}

function solvePuzzle(puzzle) {
  state.solvedPuzzles.push(puzzle.id);
  addText(puzzle.result, 'success');

  // Visual feedback
  flashPuzzleSolved();

  // Reveal items
  (puzzle.reveals || []).forEach(revealId => {
    const revealItem = GAME_DATA.items.find(i => i.id === revealId);
    if (revealItem && !state.inventory.includes(revealId)) {
      state.inventory.push(revealId);
      addText('You found: ' + revealItem.name + '!', 'success');
      highlightNewItem(revealId);
    }
  });

  renderInventory();
  highlightNewlyUnlocked();
  checkWin();
  saveState();
}

function go(sceneId) {
  if (!canExit(state.currentScene, getDirection(state.currentScene, sceneId))) {
    return;
  }
  addText('---', 'system');
  renderScene(sceneId);
}

function getDirection(fromScene, toScene) {
  const scene = GAME_DATA.scenes.find(s => s.id === fromScene);
  if (!scene || !scene.exits) return null;
  for (const [dir, target] of Object.entries(scene.exits)) {
    if (target === toScene) return dir;
  }
  return null;
}

function checkWin() {
  if (state.won) return;
  const wc = GAME_DATA.winCondition;
  if (!wc) return;
  if (state.currentScene === wc.scene &&
      wc.requires.every(req => state.inventory.includes(req))) {
    state.won = true;
    addText('', '');
    addText('*** ' + wc.description + ' ***', 'success');
    addText('', '');
    addText('CONGRATULATIONS! YOU HAVE COMPLETED FROSTBITE STATION!', 'success');
    addText('Type /restart to play again.', 'system');
  }
}

// ---- Persistence ----
function saveState() {
  try {
    localStorage.setItem('game-' + GAME_DATA.slug, JSON.stringify(state));
  } catch(e) {}
}

function loadState() {
  try {
    const saved = localStorage.getItem('game-' + GAME_DATA.slug);
    if (saved) {
      const s = JSON.parse(saved);
      Object.assign(state, s);
      return true;
    }
  } catch(e) {}
  return false;
}

// ---- Event Listeners ----
document.querySelectorAll('.cmd-btn').forEach(btn => {
  btn.onclick = () => setCommand(btn.dataset.cmd);
});

document.addEventListener('click', (e) => {
  if (e.target.classList.contains('look-target')) {
    const target = e.target.dataset.look;
    if (state.activeCommand === 'use' && state.selectedItem) {
      useItemOn(state.selectedItem, target);
    } else {
      lookAt(target);
    }
  }
});

// ---- Initialize ----
function init() {
  addText('=== FROSTBITE STATION ===', 'success');
  addText(GAME_DATA.setting, 'system');
  addText('', '');
  addText('Commands: LOOK | TAKE | USE | EXAMINE', 'system');
  addText('Click exits to move between rooms.', 'system');
  addText('---', 'system');

  if (!loadState()) {
    renderScene('landing-pad');
  } else {
    renderScene(state.currentScene);
    addText('[Game restored from save]', 'system');
  }

  // Hint toggle button
  const hintToggle = document.getElementById('hint-toggle');
  if (hintToggle) {
    hintToggle.textContent = state.hintsEnabled ? 'HINTS: ON' : 'HINTS: OFF';
    hintToggle.addEventListener('click', () => {
      state.hintsEnabled = !state.hintsEnabled;
      hintToggle.textContent = state.hintsEnabled ? 'HINTS: ON' : 'HINTS: OFF';
      if (!state.hintsEnabled) clearHintTimer();
      else startHintTimer(state.currentScene);
      saveState();
    });
  }
}

init();
