/**
 * The Clockmaker's Folly - Game Logic
 * Generated by Hex Corbin
 */

// MANDATORY: Use var for global access as per instructions
var GAME_DATA = {
  "title": "The Clockmaker's Folly",
  "slug": "the-clockmakers-folly",
  "scenes": [
    {
      "id": "scene-foyer",
      "name": "The Foyer",
      "prose": "You stand in the grand foyer of Thornwick Manor. The air smells of old wood and machine oil. Dust motes hang motionless in shafts of pale afternoon light, as if time itself has forgotten to move. A massive grandfather clock looms against the far wall, its face frozen at 11:59. The pendulum is arrested mid-swing, caught in an eternal pause. To the south, the front door — the way you came in — hangs slightly ajar, a rectangle of gray daylight beyond. A narrow hallway extends east. Upwards, a staircase winds toward shadowed floors above. To the west, a heavy oak door stands shut, its brass handle tarnished green. On a small side table near the staircase, a single brass key glints faintly, abandoned next to a stopped pocket watch.",
      "exits": {
        "east": "scene-library",
        "north": "scene-workshop",
        "up": "scene-bedroom"
      },
      "items": ["ITEM_KEY"],
      "lookDescriptions": {
        "brass key": "A heavy brass key with ornate teeth carved like clockwork gears. It fits no lock you can see from here, but it feels cold and purposeful in your imagination.",
        "front door": "The front door stands ajar, showing a rectangle of gray courtyard beyond. But something feels wrong — the light outside never changes, the leaves never fall. You cannot bring yourself to leave.",
        "grandfather clock": "The clock face is cracked, frozen eternally at 11:59. The hands tremble faintly as if trying to move. An inscription below reads: 'Time waits for no man, yet here we are.'",
        "pocket watch": "A silver pocket watch lying open on the table. Its hands are bent at impossible angles, the glass face spiderwebbed with cracks."
      },
      "puzzles": []
    },
    {
      "id": "scene-workshop",
      "name": "The Workshop",
      "prose": "Silas Thornwick's workshop is a cathedral of broken time. Workbenches groan under the weight of disassembled clocks in every state of undress — gears scattered like metallic confetti, mainsprings coiled like sleeping serpents, pendulums standing in silent ranks against the wall. The air is thick with the ghost of ticking, a phantom rhythm your ears chase but cannot catch. Light filters through grimy windows, catching on brass and steel. To the north, a door leads back to the foyer. To the west, a narrow passage opens into the library, its threshold littered with fallen pages. To the east, another door stands half-shut, revealing a dim corridor. On the main workbench sits a large clock mechanism, its guts spilled open. A locked drawer set into the bench gleams with a keyhole shaped strangely like a gear-tooth pattern.",
      "exits": {
        "south": "scene-foyer",
        "west": "scene-library",
        "east": "scene-bedroom"
      },
      "items": [],
      "lookDescriptions": {
        "clock mechanism": "The innards of a large clock, spread open like a dissected bird. Gears, springs, and levers fill every surface. Something vital is missing — an escapement gear that would set it all in motion.",
        "gears": "Brass gears of every size are scattered across the bench and floor, some no larger than a fingernail, others the width of dinner plates. None seem to fit the obvious gaps.",
        "locked drawer": "A deep drawer set into the workbench, locked with an unusual mechanism. The keyhole is cut in the shape of a clock gear, demanding a very specific key.",
        "workbench": "A scarred oak workbench covered in tools: fine screwdrivers, tiny hammers, tweezers stained dark with oil. A half-assembled pocket watch lies in pieces."
      },
      "puzzles": ["P1"]
    },
    {
      "id": "scene-library",
      "name": "The Library",
      "prose": "The library of Thornwick Manor is a labyrinth of forgotten knowledge. Floor-to-ceiling shelves groan under the weight of leather-bound volumes, their spines stamped with titles on horology, celestial mechanics, and the philosophy of time. A thick carpet swallows your footsteps. Dust hangs in stagnant columns of light from high windows. In one corner, a reading desk holds scattered notes, ink blots frozen mid-spread like dark flowers. The room smells of paper and old leather. To the east, double doors lead back to the foyer, their brass handles worn smooth by generations of hands. To the west, a short corridor leads to the workshop. But the north wall is dominated by an enormous bookshelf that blocks a doorway — or rather, a bookshelf that IS a doorway, disguised among the rest. A mechanism on its side has a gear-shaped slot, currently empty. Through the cracks around the shelf, you can see a flicker of movement in the room beyond.",
      "exits": {
        "east": "scene-workshop",
        "south": "scene-foyer",
        "west": "scene-bedroom",
        "north": "scene-bedroom"
      },
      "items": [],
      "lookDescriptions": {
        "books": "Volumes on timekeeping through the ages: water clocks, sundials, atomic precision. One title stands out — 'The Paradox of Stopped Time' — its pages are dog-eared and annotated in a shaky hand.",
        "bookshelf door": "A massive oak bookshelf that conceals a hidden doorway. A gear-shaped slot on its side is empty. Through the gaps between books, you can make out a dim room beyond.",
        "gear slot": "A recessed slot in the bookshelf door's mechanism, shaped to accept a specific brass gear. It looks like turning it would rotate the entire shelf away from the wall.",
        "reading desk": "A polished desk covered in the clockmaker's frantic notes. Diagrams of clock mechanisms mingle with increasingly paranoid scribbles about 'the tick that never ends' and 'what waits at midnight.'"
      },
      "puzzles": ["P2"]
    },
    {
      "id": "scene-bedroom",
      "name": "The Bedroom",
      "prose": "Silas Thornwick's bedroom is a capsule of a life interrupted. The bed is neatly made, the blankets pulled taut as if the occupant stepped out moments ago and plans to return. A washstand holds a pitcher and basin, the water inside undisturbed and perfectly clear. On the wall, a calendar is turned to April 1887, the 14th circled in heavy black ink. The room is oppressively still. A wardrobe stands in one corner, its doors slightly ajar, revealing hanging coats that seem to breathe with phantom movement. A safe is set into the wall near the bed, its dial cold and silent. The door to the east leads back toward the library and foyer. Another door, to the north, stands locked — its keyhole is an ornate shape that demands more than a simple key. On the nightstand, a leather journal lies open to a page filled with numbers and a single underlined phrase: 'The safe code is the hour I lost forever.'",
      "exits": {
        "east": "scene-foyer",
        "south": "scene-library",
        "west": "scene-observatory",
        "north": "scene-heart"
      },
      "items": [],
      "lookDescriptions": {
        "bed": "A four-poster bed with heavy curtains. The sheets are pristine, the pillow indented as if someone slept here recently, though the dust on the frame tells a different story.",
        "journal": "Silas Thornwick's personal journal, open to a page covered in frantic arithmetic. At the bottom, underlined twice: 'The safe code is the hour I lost forever — 1159.'",
        "safe": "A wall safe with a circular combination dial. It is locked tight, but the journal on the nightstand might hold the secret to opening it.",
        "wardrobe": "A tall oak wardrobe filled with Victorian coats and waistcoats. At the bottom, wrapped in tissue paper, a dark crystalline object glints from within a small box."
      },
      "puzzles": ["P3"]
    },
    {
      "id": "scene-observatory",
      "name": "The Observatory",
      "prose": "The observatory crowns Thornwick Manor, a circular room with a domed ceiling split by a shuttered oculus. Astronomical clocks of impossible complexity line the curved walls, their faces showing not just hours but phases of the moon, positions of planets, and cycles no living astronomer has named. A large brass telescope points through the oculus at the frozen sky. Star charts are pinned to every available surface, connected by red thread to dates and times — a web of obsession. The air is cold and thin up here. Through the oculus, the sky is a perpetual twilight, neither day nor night, stars fixed in positions that feel wrong. A staircase in the floor leads down to the bedroom. In the center of the room, the telescope's eyepiece is empty — its lens is missing. On a shelf beneath the largest astronomical clock, a small heavy object rests on a velvet cushion: a winding key, black iron, waiting.",
      "exits": {
        "down": "scene-bedroom",
        "up": "scene-heart"
      },
      "items": [],
      "lookDescriptions": {
        "astronomical clocks": "Clocks of breathtaking complexity show celestial movements. One large clock has twelve hands, each labeled with a planet, a star, or a symbol you cannot name. All are stopped at the same impossible moment.",
        "star charts": "Maps of the night sky, annotated with red ink. Dates are circled, times noted. One page shows a constellation in a configuration that hasn't existed for centuries — or won't exist for millennia.",
        "telescope": "A large brass telescope aimed at the oculus. Its eyepiece is empty — the lens has been removed. Without it, the telescope is useless, just a hollow tube pointing at eternity.",
        "winding key": "A heavy iron winding key resting on a velvet cushion. Its handle is shaped like an ouroboros — a serpent eating its tail. It feels cold and heavy, humming with latent purpose."
      },
      "puzzles": ["P4"]
    },
    {
      "id": "scene-heart",
      "name": "The Heart",
      "prose": "You have reached the heart of Thornwick Manor — the inner chamber that Silas Thornwick built to house his greatest and final creation. The room is small, circular, and dominated by a single object: the Master Clock. It stands eight feet tall, a tower of brass and glass and interlocking gears visible through transparent panels. But it is still. Silent. The great pendulum hangs motionless. The gears do not turn. The clock face, larger than a man's torso, shows no hands at all — only a blank white expanse, waiting. In the center of the clock's chest is a keyhole, shaped with the cruel elegance of a serpent devouring its own tail. The walls of the chamber are lined with smaller clocks, all synchronized, all stopped. A narrow staircase leads back down toward the observatory. There are no other exits. This is the end. The Master Clock waits. It has always waited.",
      "exits": {
        "down": "scene-observatory"
      },
      "items": [],
      "lookDescriptions": {
        "keyhole": "A keyhole shaped like a serpent eating its own tail. It demands the Master Winding Key. Something tells you that once you wind this clock, nothing will ever be the same.",
        "master clock": "A towering clock of brass and glass, silent and still. A keyhole shaped like an ouroboros waits in its center. This is what Silas built. This is what consumed him.",
        "staircase": "The only way back down, a narrow iron staircase spiraling into shadow. But you did not climb all these stairs to leave. You climbed them to end this.",
        "walls": "The walls are lined with dozens of small clocks, all showing the same frozen time: 11:59. Below each clock, a name is engraved. You do not recognize any of them."
      },
      "puzzles": ["P5"]
    }
  ],
  "items": [
    {
      "id": "ITEM_KEY",
      "name": "Brass Key",
      "description": "An ornate brass key with clock gear teeth cut into its bow. It catches the flickering light."
    },
    {
      "id": "ITEM_GEAR",
      "name": "Escapement Gear",
      "description": "A small polished brass gear with worn teeth. It looks like it belongs to a clock mechanism."
    },
    {
      "id": "ITEM_JOURNAL",
      "name": "Clockmaker's Journal",
      "description": "A leather-bound journal filled with frantic scrawls about time loops and the 'eternal tick.'"
    },
    {
      "id": "ITEM_CRYSTAL",
      "name": "Obsidian Lens",
      "description": "A dark crystalline lens that seems to drink the light around it. The edges are cut with astronomical precision."
    },
    {
      "id": "ITEM_WINDING_KEY",
      "name": "Master Winding Key",
      "description": "A heavy iron winding key, long and cold. The handle is shaped like a serpent eating its own tail."
    }
  ],
  "puzzles": [
    {
      "id": "P1",
      "scene": "scene-workshop",
      "requires": ["ITEM_KEY"],
      "action": "use brass key on locked drawer",
      "result": "The brass key turns with a satisfying click. The drawer slides open, revealing a small polished gear nestled in oil-stained velvet — the Escapement Gear, vital to any clock mechanism.",
      "reveals": ["ITEM_GEAR"],
      "target": "locked drawer"
    },
    {
      "id": "P2",
      "scene": "scene-library",
      "requires": ["ITEM_GEAR"],
      "action": "use escapement gear on gear slot",
      "result": "You fit the gear into the slot on the bookshelf door. With a deep mechanical groan, the entire shelf rotates away from the wall, revealing the hidden passage north into the Bedroom.",
      "reveals": [],
      "blocksExit": {
        "scene": "scene-library",
        "direction": "north",
        "blockedMessage": "The way north is blocked by a bookshelf door with an empty gear slot."
      },
      "target": "gear slot"
    },
    {
      "id": "P3",
      "scene": "scene-bedroom",
      "requires": ["ITEM_JOURNAL"],
      "action": "use clockmaker's journal on safe",
      "result": "The journal revealed the safe code: 1159. You dial it into the safe. It clicks open, and inside, wrapped in faded velvet, you find the Obsidian Lens — a dark crystal cut for the observatory's telescope.",
      "reveals": ["ITEM_CRYSTAL"],
      "target": "safe"
    },
    {
      "id": "P4",
      "scene": "scene-observatory",
      "requires": ["ITEM_CRYSTAL"],
      "action": "use obsidian lens on telescope",
      "result": "You slide the Obsidian Lens into the telescope's eyepiece. The dark crystal drinks the light, then focuses it into a beam that shoots through the oculus. The telescope whirs to life, sliding aside to reveal a hidden compartment — inside rests the Master Winding Key.",
      "reveals": ["ITEM_WINDING_KEY"],
      "target": "telescope"
    },
    {
      "id": "P5",
      "scene": "scene-heart",
      "requires": ["ITEM_WINDING_KEY"],
      "action": "use master winding key on master clock",
      "result": "You insert the Master Winding Key into the ouroboros-shaped keyhole. It turns once, twice, three times — and the Master Clock comes alive. Gears engage. The pendulum swings. The hands appear on the face and begin to move. Time flows again. Silas Thornwick's folly is undone. You have escaped the frozen manor. VICTORY.",
      "reveals": [],
      "target": "master clock"
    }
  ],
  "winCondition": {
    "scene": "scene-heart",
    "requires": ["ITEM_WINDING_KEY"],
    "description": "Insert the Master Winding Key into the Master Clock to restore the flow of time and escape Thornwick Manor."
  }
};

// ---- Game State ----
var state = {
  currentScene: 'scene-foyer',
  inventory: [],
  solvedPuzzles: [],
  visitedScenes: ['scene-foyer'],
  activeCommand: null,
  selectedItem: null,
  won: false
};

// ---- DOM References ----
var artDisplay = document.getElementById('art-display');
var sceneName = document.getElementById('scene-name');
var textDisplay = document.getElementById('text-display');
var invBar = document.getElementById('inventory-bar');
var exitsBar = document.getElementById('exits-bar');

// ---- Display Functions ----
function addText(text, cls = '') {
  var p = document.createElement('p');
  p.className = cls;
  p.innerHTML = text;
  textDisplay.appendChild(p);
  textDisplay.scrollTop = textDisplay.scrollHeight;
}

function clearText() { textDisplay.innerHTML = ''; }

function renderScene(sceneId) {
  var scene = GAME_DATA.scenes.find(s => s.id === sceneId);
  if (!scene) { addText('ERROR: Scene not found!', 'error'); return; }

  state.currentScene = sceneId;
  if (!state.visitedScenes.includes(sceneId)) state.visitedScenes.push(sceneId);

  // Update scene name
  sceneName.textContent = scene.name.toUpperCase();

  // Update art
  var artKey = 'scene-' + sceneId.replace('scene-', '');
  var artHtml = null;
  if (window.GAME_ART && window.GAME_ART[artKey]) {
    artHtml = window.GAME_ART[artKey];
  } else if (window.GAME_ART && window.GAME_ART[sceneId]) {
    artHtml = window.GAME_ART[sceneId];
  }

  if (artHtml) {
    artDisplay.innerHTML = artHtml;
  } else {
    artDisplay.innerHTML = '<span class="no-art">[ ' + scene.name.toUpperCase() + ' ]</span>';
  }

  // Display prose
  clearText();
  addText(scene.prose);

  // Show available items (not yet taken)
  var availableItems = (scene.items || []).filter(itemId =>
    !state.inventory.includes(itemId)
  );
  if (availableItems.length > 0) {
    var itemNames = availableItems.map(id => {
      var item = GAME_DATA.items.find(i => i.id === id);
      return item ? `<span class="look-target" data-look="${id}">${item.name}</span>` : id;
    });
    addText('You notice: ' + itemNames.join(', '), 'system');
  }

  // Render exits
  renderExits(scene.exits || {});

  // Render inventory
  renderInventory();

  // Check win condition
  checkWin();

  // Save state
  saveState();
}

function canExit(sceneId, direction) {
  var exit = GAME_DATA.scenes.find(s => s.id === sceneId)?.exits?.[direction];
  if (!exit) return false;
  
  // Check if any unsolved puzzle blocks this exit
  var blocker = GAME_DATA.puzzles.find(p =>
    p.blocksExit &&
    p.blocksExit.scene === sceneId &&
    p.blocksExit.direction === direction &&
    !state.solvedPuzzles.includes(p.id)
  );
  
  if (blocker) {
    addText(`[The way ${direction} is blocked. ${blocker.blocksExit.blockedMessage || 'Something prevents you from going that way.'}]`, 'locked');
    return false;
  }
  return true;
}

function renderExits(exits) {
  exitsBar.innerHTML = '';
  var directions = ['north', 'south', 'east', 'west', 'up', 'down'];
  directions.forEach(dir => {
    if (exits[dir]) {
      var btn = document.createElement('button');
      btn.className = 'exit-btn available';
      btn.textContent = dir.toUpperCase();
      btn.onclick = () => {
        if (canExit(state.currentScene, dir)) {
          go(exits[dir]);
        }
      };
      exitsBar.appendChild(btn);
    }
  });
}

function renderInventory() {
  var items = invBar.querySelectorAll('.inv-item');
  items.forEach(el => el.remove());
  var empty = document.getElementById('inv-empty');

  if (state.inventory.length === 0) {
    empty.style.display = '';
  } else {
    empty.style.display = 'none';
    state.inventory.forEach(itemId => {
      var item = GAME_DATA.items.find(i => i.id === itemId);
      if (!item) return;
      var el = document.createElement('span');
      el.className = 'inv-item' + (state.selectedItem === itemId ? ' selected' : '');
      el.textContent = item.name;
      el.onclick = () => selectItem(itemId);
      invBar.appendChild(el);
    });
  }
}

// ---- Command Handlers ----
function setCommand(cmd) {
  state.activeCommand = cmd;
  document.querySelectorAll('.cmd-btn').forEach(b => {
    b.classList.toggle('active', b.dataset.cmd === cmd);
  });
  
  var scene = GAME_DATA.scenes.find(s => s.id === state.currentScene);
  
  if (cmd === 'look') {
    if (scene && scene.lookDescriptions) {
      var targets = Object.keys(scene.lookDescriptions);
      if (targets.length > 0) {
        addText('You can examine: ' + targets.map(t =>
          `<span class="look-target" data-look="${t}">${t}</span>`
        ).join(', '), 'system');
      }
    }
  } else if (cmd === 'use') {
    if (state.inventory.length > 0) {
      addText('Select an item from your inventory, then click what to use it on.', 'system');
    } else {
      addText('You have nothing to use.', 'system');
    }
  } else if (cmd === 'take') {
    var available = (scene.items || []).filter(id => !state.inventory.includes(id));
    if (available.length > 0) {
      available.forEach(id => takeItem(id));
    } else {
      addText('Nothing here to take.', 'system');
    }
  }
}

function selectItem(itemId) {
  state.selectedItem = state.selectedItem === itemId ? null : itemId;
  renderInventory();
  if (state.selectedItem) {
    var item = GAME_DATA.items.find(i => i.id === itemId);
    addText(`Selected: ${item.name}. Click USE, then a target.`, 'system');
  }
}

function takeItem(itemId) {
  if (state.inventory.includes(itemId)) return;
  var item = GAME_DATA.items.find(i => i.id === itemId);
  if (!item) return;
  var scene = GAME_DATA.scenes.find(s => s.id === state.currentScene);
  if (!scene || !(scene.items || []).includes(itemId)) return;

  state.inventory.push(itemId);
  addText(`You picked up: ${item.name}`, 'success');
  addText(item.description, 'system');
  
  // Visual feedback for item
  renderInventory();
  saveState();
}

function lookAt(target) {
  var scene = GAME_DATA.scenes.find(s => s.id === state.currentScene);
  if (scene && scene.lookDescriptions && scene.lookDescriptions[target]) {
    addText(scene.lookDescriptions[target]);
  } else {
    // Check if it's an item in inventory or scene
    var item = GAME_DATA.items.find(i => i.id === target);
    if (item) {
      addText(item.description);
    } else {
      addText('Nothing interesting about that.', 'system');
    }
  }
}

function triggerPuzzleFeedback() {
  artDisplay.classList.add('puzzle-solved');
  setTimeout(() => artDisplay.classList.remove('puzzle-solved'), 600);
}

function useItemOn(itemId, targetId) {
  var puzzle = GAME_DATA.puzzles.find(p =>
    p.scene === state.currentScene &&
    p.requires.includes(itemId) &&
    (p.target === targetId || p.id === targetId) &&
    !state.solvedPuzzles.includes(p.id)
  );

  if (puzzle) {
    state.solvedPuzzles.push(puzzle.id);
    addText(puzzle.result, 'success');
    triggerPuzzleFeedback();
    
    // Reveal items
    (puzzle.reveals || []).forEach(revealId => {
      var revealItem = GAME_DATA.items.find(i => i.id === revealId);
      if (revealItem) {
        state.inventory.push(revealId);
        addText(`You found: ${revealItem.name}!`, 'success');
      }
    });

    // Check if exit was unlocked
    if (puzzle.blocksExit) {
      renderExits(GAME_DATA.scenes.find(s => s.id === state.currentScene).exits);
    }
    
    renderInventory();
    checkWin();
    saveState();
  } else {
    addText("That doesn't seem to work here.", 'system');
  }
}

function go(sceneId) {
  addText('---', 'system');
  renderScene(sceneId);
}

function checkWin() {
  if (state.won) return;
  
  // Check if we solved P5 (the heart puzzle)
  if (state.solvedPuzzles.includes('P5')) {
    state.won = true;
    addText('', '');
    addText('*** TIME FLOWS AGAIN ***', 'success');
    addText('', '');
    addText('CONGRATULATIONS! YOU HAVE COMPLETED THE GAME!', 'success');
  }
}

// ---- Persistence ----
function saveState() {
  try {
    localStorage.setItem('game-' + GAME_DATA.slug, JSON.stringify(state));
  } catch(e) {}
}

function loadState() {
  try {
    var saved = localStorage.getItem('game-' + GAME_DATA.slug);
    if (saved) {
      var s = JSON.parse(saved);
      Object.assign(state, s);
      return true;
    }
  } catch(e) {}
  return false;
}

// ---- Event Listeners ----
document.querySelectorAll('.cmd-btn').forEach(btn => {
  btn.onclick = () => setCommand(btn.dataset.cmd);
});

document.addEventListener('click', (e) => {
  if (e.target.classList.contains('look-target')) {
    var target = e.target.dataset.look;
    if (state.activeCommand === 'use' && state.selectedItem) {
      useItemOn(state.selectedItem, target);
    } else {
      lookAt(target);
    }
  }
});

// ---- Initialize ----
function init() {
  if (Object.keys(GAME_DATA).length === 0) {
    addText('ERROR: No game data loaded.', 'error');
    return;
  }

  addText('=== ' + GAME_DATA.title.toUpperCase() + ' ===', 'success');
  addText(GAME_DATA.setting, 'system');
  addText('', '');
  addText('Commands: LOOK | TAKE | USE | EXAMINE', 'system');
  addText('---', 'system');

  if (!loadState()) {
    renderScene('scene-foyer');
  } else {
    renderScene(state.currentScene);
    addText('[Game restored from save]', 'system');
  }
}

window.onload = init;
