// Game #36: The Static Cabin
// Generated by Hex Corbin - Retro Game Logic Engineer
// Data-driven adventure game engine

const GAME_DATA = {
  title: "The Static Cabin",
  slug: "the-static-cabin",
  scenes: [
    {
      id: "porch",
      name: "The Porch",
      prose: "The screen door bangs rhythmically against the frame. A shimmering wall of grey static swallows the trees just ten feet from the steps. To the north, the heavy oak door leads into the main cabin. To the north, the jagged silhouette of the radio tower looms.",
      exits: { north: "main-room", tower: "tower-base" },
      items: [],
      puzzles: ["puzzle-tower-access"],
      lookDescriptions: {
        "screen-door": "Banging in the wind.",
        "static-wall": "A grinding visual roar.",
        "tower-silhouette": "Jagged and dark."
      }
    },
    {
      id: "main-room",
      name: "Main Room",
      prose: "The cabin is filled with wood-grain and glowing vacuum tubes. A cast-iron stove sits in the corner. A wall of radio equipment hisses nearby. Above, a wooden trapdoor is sealed into the ceiling.",
      exits: { south: "porch", west: "kitchenette", up: "attic" },
      items: [],
      puzzles: ["puzzle-stove", "puzzle-winch", "puzzle-radio"],
      lookDescriptions: {
        "radio-wall": "Dials are spinning wildly.",
        "stove": "An old Pioneer model. The door is fused.",
        "ceiling-trapdoor": "Leads to the crawlspace above. Missing a handle."
      }
    },
    {
      id: "kitchenette",
      name: "The Kitchenette",
      prose: "A cramped corner smelling of woodsmoke. Shelves of canned goods line the walls. A heavy wooden trapdoor in the floor is secured by a thick padlock.",
      exits: { east: "main-room", down: "cellar" },
      items: ["brass-oil-can"],
      puzzles: ["puzzle-padlock"],
      lookDescriptions: {
        "sink": "Morse code drips.",
        "floor-trapdoor": "Heavy timber.",
        "rusted-drawer": "Jammed with old tools."
      }
    },
    {
      id: "attic",
      name: "Attic Crawlspace",
      prose: "The air is thick with dust and dry cedar. A single window looks out at the solar-flushed sky.",
      exits: { down: "main-room" },
      items: ["heavy-wrench"],
      puzzles: [],
      lookDescriptions: {
        "window": "Hot to the touch.",
        "beams": "Burnt scorch marks.",
        "wrench": "Massive industrial equipment."
      }
    },
    {
      id: "cellar",
      name: "Root Cellar",
      prose: "A cold, earth-walled room. The smell of stored potatoes and iron is sharp.",
      exits: { up: "kitchenette" },
      items: ["vacuum-tube"],
      puzzles: [],
      lookDescriptions: {
        "walls": "Roots are vibrating.",
        "tube-caddy": "An 'Electro-Voice' model.",
        "darkness": "Deep and safe."
      }
    },
    {
      id: "tower-base",
      name: "Radio Tower Base",
      prose: "The ground is scorched black around the structure. The tower screams as it vibrates in the gale. A control-box is mounted to its base.",
      exits: { south: "porch" },
      items: [],
      puzzles: ["puzzle-reset"],
      lookDescriptions: {
        "tower": "Lightning rod for the cosmos.",
        "control-box": "Magnetic lock lit red.",
        "scorched-earth": "Carbonized grass."
      }
    }
  ],
  items: [
    {
      id: "brass-oil-can",
      name: "Brass Oil Can",
      description: "An old-fashioned oil can with a precision spout.",
      foundIn: "kitchenette"
    },
    {
      id: "hand-crank",
      name: "Hand Crank",
      description: "A heavy iron T-handle for a manual winch.",
      foundIn: "main-room"
    },
    {
      id: "heavy-wrench",
      name: "Heavy Wrench",
      description: "A massive steel pipe wrench.",
      foundIn: "attic"
    },
    {
      id: "vacuum-tube",
      name: "Vacuum Tube",
      description: "A glass 'glow-tube' from a high-power radio set.",
      foundIn: "cellar"
    },
    {
      id: "magnetic-keycard",
      name: "Magnetic Keycard",
      description: "A plain white card with a magnetic strip.",
      foundIn: "main-room"
    }
  ],
  puzzles: [
    {
      id: "puzzle-tower-access",
      scene: "porch",
      requires: [],
      action: "walk north",
      result: "You enter the cabin, escaping the static roar.",
      reveals: ["main-room"],
      blocksExit: { scene: "porch", direction: "tower", blockedMessage: "The static wall is too intense to approach the tower." }
    },
    {
      id: "puzzle-stove",
      scene: "main-room",
      requires: ["brass-oil-can"],
      action: "use oil-can on stove",
      result: "The door swings open, revealing a hand-crank in the ash.",
      reveals: ["hand-crank"]
    },
    {
      id: "puzzle-winch",
      scene: "main-room",
      requires: ["hand-crank"],
      action: "use hand-crank on winch",
      result: "The trapdoor drops, revealing the ladder to the attic.",
      reveals: ["attic"],
      blocksExit: { scene: "main-room", direction: "up", blockedMessage: "The trapdoor is sealed shut. It needs a mechanism to open it." }
    },
    {
      id: "puzzle-padlock",
      scene: "kitchenette",
      requires: ["heavy-wrench"],
      action: "use wrench on padlock",
      result: "The padlock snaps, revealing the cellar entrance.",
      reveals: ["cellar"],
      blocksExit: { scene: "kitchenette", direction: "down", blockedMessage: "The padlock is thick and rusted. Something strong could break it." }
    },
    {
      id: "puzzle-radio",
      scene: "main-room",
      requires: ["vacuum-tube"],
      action: "use tube on radio",
      result: "The radio hums to life and ejects a magnetic-keycard.",
      reveals: ["magnetic-keycard"]
    },
    {
      id: "puzzle-reset",
      scene: "tower-base",
      requires: ["magnetic-keycard"],
      action: "use magnetic-keycard on control-box",
      result: "The code is accepted. Reality stabilizes.",
      reveals: []
    }
  ],
  winCondition: {
    scene: "tower-base",
    requires: ["magnetic-keycard"],
    description: "The reset sequence triggers. Reality stabilizes. The end."
  }
};

// ============================================
// STATE MANAGEMENT
// ============================================

let state = {
  currentScene: "porch",
  inventory: [],
  solvedPuzzles: [],
  visitedScenes: ["porch"],
  gameWon: false
};

// ============================================
// DOM ELEMENTS
// ============================================

let sceneNameEl, sceneProseEl, outputEl, artDisplayEl, exitsBarEl, inventoryBarEl, commandBarEl;

function initDOM() {
  sceneNameEl = document.getElementById('scene-name');
  sceneProseEl = document.getElementById('scene-prose');
  outputEl = document.getElementById('output');
  artDisplayEl = document.querySelector('.art-display');
  exitsBarEl = document.getElementById('exits-bar');
  inventoryBarEl = document.getElementById('inventory-bar');
  commandBarEl = document.getElementById('command-bar');
}

// ============================================
// HELPER FUNCTIONS
// ============================================

function getScene(sceneId) {
  return GAME_DATA.scenes.find(s => s.id === sceneId);
}

function getItem(itemId) {
  return GAME_DATA.items.find(i => i.id === itemId);
}

function getPuzzle(puzzleId) {
  return GAME_DATA.puzzles.find(p => p.id === puzzleId);
}

function hasItem(itemId) {
  return state.inventory.includes(itemId);
}

function isPuzzleSolved(puzzleId) {
  return state.solvedPuzzles.includes(puzzleId);
}

function addText(message, className = '') {
  const line = document.createElement('div');
  line.className = className;
  line.textContent = message;
  outputEl.appendChild(line);
  outputEl.scrollTop = outputEl.scrollHeight;
}

function clearOutput() {
  outputEl.innerHTML = '';
}

// ============================================
// LOCKED EXITS CHECK
// ============================================

function canExit(sceneId, direction) {
  const scene = getScene(sceneId);
  if (!scene || !scene.exits[direction]) return false;

  // Check if any unsolved puzzle blocks this exit
  const blocker = GAME_DATA.puzzles.find(p =>
    p.blocksExit?.scene === sceneId &&
    p.blocksExit?.direction === direction &&
    !isPuzzleSolved(p.id)
  );

  if (blocker) {
    addText(`[The way ${direction} is blocked. ${blocker.blockedMessage}]`, 'locked');
    return false;
  }

  return true;
}

// ============================================
// SCENE RENDERING
// ============================================

function renderScene() {
  const scene = getScene(state.currentScene);
  if (!scene) return;

  // Mark as visited
  if (!state.visitedScenes.includes(scene.id)) {
    state.visitedScenes.push(scene.id);
  }

  // Update scene title and prose
  sceneNameEl.textContent = scene.name;
  sceneProseEl.textContent = scene.prose;

  // Clear output
  clearOutput();
  addText(scene.prose);

  // Render exits (respects locked exits)
  renderExits(scene);

  // Render scene items
  renderSceneItems(scene);

  // Render inventory
  renderInventory();

  // Check for first-time visit hints
  if (state.visitedScenes.length === 1) {
    addText("(Use LOOK to examine things, TAKE to pick up items, USE to interact.)");
  }
}

function renderExits(scene) {
  exitsBarEl.innerHTML = '';
  
  // Build list of available exits (unlocked)
  const availableExits = [];
  for (const [direction, targetSceneId] of Object.entries(scene.exits)) {
    if (canExit(scene.id, direction)) {
      availableExits.push({ direction, targetSceneId });
    }
  }

  // Create exit buttons
  availableExits.forEach(({ direction, targetSceneId }) => {
    const btn = document.createElement('button');
    btn.className = 'exit-btn';
    btn.textContent = direction.toUpperCase();
    btn.addEventListener('click', () => handleGo(direction));
    exitsBarEl.appendChild(btn);
  });

  // Show message if no exits
  if (availableExits.length === 0) {
    const msg = document.createElement('span');
    msg.textContent = '[no way out]';
    msg.style.color = '#888';
    exitsBarEl.appendChild(msg);
  }
}

function renderSceneItems(scene) {
  // Items in the scene that haven't been taken yet
  const availableItems = scene.items.filter(itemId => !hasItem(itemId));
  
  // Add look options for lookDescriptions
  const lookOptions = Object.keys(scene.lookDescriptions || {});

  // If we have scene items, show them in a separate section
  if (availableItems.length > 0) {
    const itemsContainer = document.createElement('div');
    itemsContainer.className = 'scene-items';
    itemsContainer.style.marginTop = '8px';
    itemsContainer.style.fontStyle = 'italic';
    itemsContainer.textContent = `You see: ${availableItems.map(id => getItem(id).name).join(', ')}`;
    outputEl.appendChild(itemsContainer);
  }

  // Add command bar verbs
  updateCommandBar(scene, availableItems, lookOptions);
}

function updateCommandBar(scene, sceneItems, lookOptions) {
  commandBarEl.innerHTML = '';
  
  // LOOK at scene items
  sceneItems.forEach(itemId => {
    const btn = document.createElement('button');
    btn.className = 'cmd-btn';
    btn.textContent = `LOOK ${getItem(itemId).name.toUpperCase()}`;
    btn.addEventListener('click', () => handleLookAtItem(itemId));
    commandBarEl.appendChild(btn);
  });

  // TAKE scene items
  sceneItems.forEach(itemId => {
    const btn = document.createElement('button');
    btn.className = 'cmd-btn';
    btn.textContent = `TAKE ${getItem(itemId).name.toUpperCase()}`;
    btn.addEventListener('click', () => handleTake(itemId));
    commandBarEl.appendChild(btn);
  });

  // LOOK at environment details
  lookOptions.forEach(descKey => {
    const btn = document.createElement('button');
    btn.className = 'cmd-btn';
    btn.textContent = `LOOK ${descKey.toUpperCase()}`;
    btn.addEventListener('click', () => {
      addText(scene.lookDescriptions[descKey]);
      triggerArtFlash();
    });
    commandBarEl.appendChild(btn);
  });

  // INVENTORY button if inventory not empty
  if (state.inventory.length > 0) {
    const invBtn = document.createElement('button');
    invBtn.className = 'cmd-btn';
    invBtn.textContent = 'INVENTORY';
    invBtn.addEventListener('click', () => {
      const items = state.inventory.map(id => getItem(id).name).join(', ');
      addText(`You are carrying: ${items}`);
    });
    commandBarEl.appendChild(invBtn);
  }

  // EXAMINE inventory items for using
  state.inventory.forEach(itemId => {
    const item = getItem(itemId);
    const btn = document.createElement('button');
    btn.className = 'cmd-btn';
    btn.textContent = `USE ${item.name.toUpperCase()}`;
    btn.addEventListener('click', () => handleUse(itemId));
    commandBarEl.appendChild(btn);
  });
}

function renderInventory() {
  inventoryBarEl.innerHTML = '';
  
  if (state.inventory.length === 0) {
    inventoryBarEl.innerHTML = '<span style="color:#888;font-size:0.9em;">Inventory empty</span>';
    return;
  }

  state.inventory.forEach(itemId => {
    const item = getItem(itemId);
    const btn = document.createElement('button');
    btn.className = 'inv-item';
    btn.textContent = item.name;
    btn.title = item.description;
    btn.addEventListener('click', () => handleUse(itemId));
    inventoryBarEl.appendChild(btn);
  });
}

// ============================================
// COMMAND HANDLERS
// ============================================

function handleLook() {
  const scene = getScene(state.currentScene);
  addText(scene.prose);
}

function handleLookAtItem(itemId) {
  const item = getItem(itemId);
  addText(item.description);
  triggerArtFlash();
}

function handleTake(itemId) {
  // Check if item is in current scene and not already taken
  const scene = getScene(state.currentScene);
  if (scene.items.includes(itemId) && !state.inventory.includes(itemId)) {
    state.inventory.push(itemId);
    addText(`You take the ${getItem(itemId).name}.`);
    renderScene(); // Re-render to update display
  } else {
    addText("You don't see that here.");
  }
}

function handleUse(itemId) {
  const item = getItem(itemId);
  const scene = getScene(state.currentScene);
  
  // Find puzzle that matches this use action in current scene
  const puzzle = GAME_DATA.puzzles.find(p =>
    p.scene === state.currentScene &&
    p.requires.includes(itemId) &&
    !isPuzzleSolved(p.id)
  );

  if (!puzzle) {
    addText(`You can't use the ${item.name} here.`);
    return;
  }

  // Check if player has all required items
  const missingItems = puzzle.requires.filter(reqId => !hasItem(reqId));
  if (missingItems.length > 0) {
    addText(`You need something else first.`);
    return;
  }

  // Solve the puzzle
  solvePuzzle(puzzle);
}

function handleGo(direction) {
  // Check for movement-triggered puzzles (e.g., "walk north")
  const scene = getScene(state.currentScene);
  const moveAction = `walk ${direction}`;
  const movePuzzle = GAME_DATA.puzzles.find(p =>
    p.scene === state.currentScene &&
    !isPuzzleSolved(p.id) &&
    p.action === moveAction
  );

  if (movePuzzle) {
    // Check requirements
    const missingItems = movePuzzle.requires.filter(reqId => !hasItem(reqId));
    if (missingItems.length > 0) {
      addText(`You need something before you can go that way.`);
      return;
    }
    // Solve the puzzle first
    solvePuzzle(movePuzzle);
  }

  // Now check if exit is allowed (blockers may have been cleared)
  if (!canExit(state.currentScene, direction)) {
    return;
  }

  const targetSceneId = scene.exits[direction];
  state.currentScene = targetSceneId;
  renderScene();
}

function handleExamine() {
  // Alias for LOOK
  handleLook();
}

// ============================================
// PUZZLE LOGIC
// ============================================

function solvePuzzle(puzzle) {
  // Mark puzzle solved
  state.solvedPuzzles.push(puzzle.id);
  
  // Show result
  addText(puzzle.result);
  
  // Visual feedback
  triggerArtFlash();
  
  // Handle reveals: add items to current scene (if valid)
  if (puzzle.reveals && puzzle.reveals.length > 0) {
    puzzle.reveals.forEach(entry => {
      const item = getItem(entry);
      if (item) {
        // Add the revealed item to the current scene's items
        const currentScene = getScene(state.currentScene);
        if (currentScene && !currentScene.items.includes(entry)) {
          currentScene.items.push(entry);
          addText(`You now see: ${item.name}`);
        }
      } else {
        // Entry is not an item (could be scene ID); ignore
      }
    });
  }

  // Check if this puzzle unblocks any exits
  if (puzzle.blocksExit) {
    addText(`[Exit ${puzzle.blocksExit.direction} is now unlocked!]`, 'success');
    triggerExitUnlock();
  }

  // Re-render scene to update buttons and items
  setTimeout(() => {
    renderScene();
  }, 100);

  // Check win condition
  checkWinCondition();
}

function triggerArtFlash() {
  if (artDisplayEl) {
    artDisplayEl.classList.add('puzzle-solved');
    setTimeout(() => {
      artDisplayEl.classList.remove('puzzle-solved');
    }, 600);
  }
}

function triggerExitUnlock() {
  if (exitsBarEl) {
    // Add visual pulse class to newly unlocked exits
    const exitBtns = exitsBarEl.querySelectorAll('.exit-btn');
    exitBtns.forEach(btn => {
      btn.classList.add('newly-unlocked');
      setTimeout(() => {
        btn.classList.remove('newly-unlocked');
      }, 3000);
    });
  }
}

function triggerItemGlow(itemId) {
  // Find the inventory button for this item
  setTimeout(() => {
    const invBtns = inventoryBarEl.querySelectorAll('.inv-item');
    invBtns.forEach(btn => {
      if (btn.textContent === getItem(itemId).name) {
        btn.classList.add('item-new');
        setTimeout(() => {
          btn.classList.remove('item-new');
        }, 2000);
      }
    });
  }, 100);
}

// ============================================
// WIN CONDITION
// ============================================

function checkWinCondition() {
  const win = GAME_DATA.winCondition;
  
  // Check if we're in the right scene with required item
  if (state.currentScene === win.scene) {
    const hasRequired = win.requires.every(reqId => hasItem(reqId));
    if (hasRequired && !state.gameWon) {
      state.gameWon = true;
      setTimeout(() => {
        addText('');
        addText('*** ' + win.description + ' ***', 'win');
        addText('You have completed The Static Cabin!', 'win');
        
        // Disable command buttons
        document.querySelectorAll('.cmd-btn, .exit-btn').forEach(btn => {
          btn.disabled = true;
          btn.style.opacity = '0.5';
        });
      }, 500);
    }
  }
}

// ============================================
// EVENT LISTENERS & INITIALIZATION
// ============================================

function init() {
  initDOM();
  
  // Bind keyboard shortcuts (optional)
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') {
      // Could be used for help or menu
    }
  });

  // Initial render
  renderScene();
  
  addText(`Welcome to ${GAME_DATA.title}!`);
  addText("Type or click commands to explore.");
}

// Start the game when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', init);
} else {
  init();
}