// ============================================================
// CURTAIN CALL - Game Logic
// Generated by Hex Corbin (Gameplay Coder)
// A haunted 1920s grand theater point-and-click adventure
// ============================================================

// ---- Game Data (embedded from game-script.json) ----
var GAME_DATA = {
  "title": "Curtain Call",
  "slug": "curtain-call",
  "number": 7,
  "setting": "A haunted 1920s grand theater where the final performance never ended. The audience is frozen in time, the actors trapped in their roles, and the show must go on... forever.",
  "characters": [
    {
      "id": "stage-manager",
      "name": "The Stage Manager",
      "description": "A ghostly figure in a black vest, forever checking his watch. He appears only in the catwalk, muttering about cues and missed entrances."
    },
    {
      "id": "leading-lady",
      "name": "Eleanor Vance",
      "description": "The theater's star, trapped in her dressing room mirror. Her faint humming can be heard, singing the same aria on loop."
    }
  ],
  "items": [
    {
      "id": "theater-key",
      "name": "Brass Theater Key",
      "description": "A heavy brass key with intricate filigree. It smells of old metal and dust.",
      "foundIn": "foyer",
      "usedIn": "foyer",
      "usedOn": "puzzle-1"
    },
    {
      "id": "ghost-light",
      "name": "Ghost Light",
      "description": "A single bare bulb on a metal stand, casting a pale glow. It's warm to the touch.",
      "foundIn": "auditorium",
      "usedIn": "auditorium",
      "usedOn": "puzzle-2"
    },
    {
      "id": "makeup-kit",
      "name": "Makeup Kit",
      "description": "A vintage tin filled with greasepaint, powder, and rouge. The mirror inside is cracked.",
      "foundIn": "dressing-rooms",
      "usedIn": "backstage",
      "usedOn": "puzzle-3"
    },
    {
      "id": "cue-sheet",
      "name": "Lighting Cue Sheet",
      "description": "A sheet of paper with symbols: circle, triangle, square, cross. Handwritten notes indicate a sequence.",
      "foundIn": "catwalk",
      "usedIn": "catwalk",
      "usedOn": "puzzle-4"
    },
    {
      "id": "conductor-baton",
      "name": "Conductor's Baton",
      "description": "A slender ebony baton with a silver tip. It feels unnaturally cold.",
      "foundIn": "catwalk",
      "usedIn": "stage",
      "usedOn": "puzzle-5"
    },
    {
      "id": "illuminated-mirror",
      "name": "Illuminated Mirror",
      "description": "The ghost light reflected in the makeup kit's mirror, creating a beam of focused light. It hums softly.",
      "foundIn": null,
      "usedIn": "stage",
      "usedOn": "puzzle-5"
    }
  ],
  "scenes": [
    {
      "id": "foyer",
      "name": "The Grand Foyer",
      "prose": "The grand theater foyer is frozen in time. Dust motes hang in the amber light of a single chandelier. A ticket booth's window is smashed, glass scattered like ice. Marble floors reflect the hollow silence. To the north, ornate double doors lead to the auditorium, but a heavy chain and padlock secure them. A brass key glints inside the ticket booth. The air smells of old velvet and something else\u2014burnt wiring, maybe, or distant ozone. A staircase to the east climbs into darkness, but the way is blocked by fallen scenery flats.",
      "exits": {
        "north": "auditorium"
      },
      "items": ["theater-key"],
      "puzzles": ["puzzle-1"],
      "lookDescriptions": {
        "ticket booth": "The glass is shattered inward. Inside, a brass key rests on a dusty ledger.",
        "chandelier": "One bulb still glows, casting long shadows. The crystals are clouded with grime.",
        "chain": "A thick chain wraps the auditorium doors' handles, secured with a heavy padlock.",
        "staircase": "The stairs lead up to a mezzanine, but collapsed scenery blocks the way entirely."
      }
    },
    {
      "id": "auditorium",
      "name": "The Auditorium",
      "prose": "The auditorium stretches away into velvet darkness. Rows of empty seats face a stage where a single ghost light glows\u2014a bare bulb on a stand, casting long shadows. The curtain is half-raised, revealing a dusty proscenium. A faint scent of perfume and mothballs lingers. To the east, a door marked 'BACKSTAGE' stands ajar, but no light comes from within. The ghost light seems movable. On the stage floor, a single white rose lies wilted. From the catwalk above, a soft creaking suggests something moving in the grid.",
      "exits": {
        "east": "backstage"
      },
      "items": ["ghost-light"],
      "puzzles": ["puzzle-2"],
      "lookDescriptions": {
        "ghost light": "A traditional theater superstition\u2014a single bulb left on stage to ward off ghosts. It's warm, as if recently lit.",
        "seats": "Velvet upholstery, worn thin. Some seats have playbills left behind, faded to illegibility.",
        "stage": "The wooden boards are scarred from decades of use. A faint outline of chalk marks remains.",
        "rose": "A white rose, perfectly preserved though wilted. No stem\u2014just the blossom.",
        "backstage door": "A heavy metal door with a push-bar. The sign is faded but legible."
      }
    },
    {
      "id": "backstage",
      "name": "Backstage",
      "prose": "Backstage is a labyrinth of ropes, pulleys, and forgotten props. A large mirror hangs cracked on one wall, reflecting distorted glimpses of the space. Wooden flats lean against walls\u2014painted forests, castle interiors. A ladder leads up to the catwalk, but several rungs are missing, making it impassable. To the south, a hallway leads to dressing rooms. The air is thick with the smell of greasepaint and dust. A workbench holds scattered tools: a screwdriver, a coil of rope, a tin of stage blood dried black.",
      "exits": {
        "south": "dressing-rooms",
        "up": "catwalk"
      },
      "items": [],
      "puzzles": ["puzzle-3"],
      "lookDescriptions": {
        "mirror": "A full-length mirror, its surface cracked like a spiderweb. Your reflection looks distorted, wavering.",
        "ladder": "The lower rungs are broken off. You'd need something to extend it to reach the catwalk.",
        "workbench": "Tools lie as if dropped mid\u2009repair. The stage blood tin is rusted shut.",
        "ropes": "Heavy hemp ropes, some still tied off. They smell of resin and old sweat."
      }
    },
    {
      "id": "dressing-rooms",
      "name": "Dressing Rooms",
      "prose": "A narrow hallway lined with dressing room doors, each marked with a star. One door is slightly open; inside, a vanity table littered with makeup tins, powder puffs, and a silver hairbrush. A costume rack holds sequined gowns and moth\u2009eaten tuxedos. A faint humming seems to come from the mirror\u2014a woman's voice, singing a tune you don't recognize. The air is cold. On the vanity, a makeup kit sits open, its contents still vibrant. The hallway continues but ends at a bricked\u2009up archway.",
      "exits": {
        "north": "backstage"
      },
      "items": ["makeup-kit"],
      "puzzles": [],
      "lookDescriptions": {
        "vanity table": "The mirror is spotted with age. Lipstick stains the edge. A photograph\u2014a woman in a glittering dress\u2014is tucked into the frame.",
        "makeup kit": "A hinged tin with compartments for powders and creams. The mirror inside is small but intact.",
        "costume rack": "Garments hung with care, now dusty and fragile. A sequined dress sparkles even in the dim light.",
        "humming": "The sound seems to emanate from the mirror itself. It's a sad, slow aria."
      }
    },
    {
      "id": "catwalk",
      "name": "Catwalk",
      "prose": "High above the stage, the catwalk is a metal gridwalk suspended in darkness. A lighting control board blinks with dead indicators. A cue sheet is pinned nearby, scribbled with symbols. Far below, the ghost light is a tiny beacon. A conductor's baton rests on a railing, as if just set down. The grid stretches east over the stage, but a section has collapsed, blocking access. The air hums with residual electricity. From here, the whole theater feels like a carcass waiting to be filled.",
      "exits": {
        "east": "stage"
      },
      "items": ["cue-sheet", "conductor-baton"],
      "puzzles": ["puzzle-4"],
      "lookDescriptions": {
        "lighting board": "A console of sliders and buttons. Most are dark; a few LEDs flicker weakly.",
        "cue sheet": "Handwritten symbols: circle, triangle, square, cross. An arrow points to the sequence circle\u2009triangle\u2009square\u2009cross.",
        "baton": "An elegant ebony baton. The silver tip is tarnished. It feels colder than the surrounding air.",
        "collapsed grid": "A section of the catwalk has given way, leaving a gap too wide to cross."
      }
    },
    {
      "id": "stage",
      "name": "The Stage",
      "prose": "The stage is a pool of dark velvet. A single spotlight hangs dead above. The curtain ropes dangle like nooses. A sense of profound stillness weighs the air\u2014the kind that comes before a scream. A large, ornate mirror stands upstage, its surface clouded as if breathed on. At center stage, a music stand holds a scorched score. This is where it happened\u2014where the performance froze. To win, you must break the curse. Use the illuminated mirror and conductor's baton to shatter the spell holding the theater in time.",
      "exits": {},
      "items": [],
      "puzzles": ["puzzle-5"],
      "lookDescriptions": {
        "spotlight": "A heavy\u2009duty theatrical light, its lens cracked. It points straight down at a mark on the floor.",
        "curtain ropes": "Thick ropes that raise and lower the main curtain. They're knotted in complex patterns.",
        "ornate mirror": "A gilded mirror, taller than a person. The glass is fogged, but something moves in its depths.",
        "music stand": "A black metal stand holding a sheet of music. The notes are blurred, as if melted by heat."
      }
    }
  ],
  "puzzles": [
    {
      "id": "puzzle-1",
      "scene": "foyer",
      "requires": ["theater-key"],
      "action": "Use brass theater key on padlocked chain",
      "result": "The padlock clicks open. The chain slithers to the floor with a heavy thud. The auditorium doors swing inward, revealing darkness beyond.",
      "reveals": ["auditorium"],
      "blocksExit": { "scene": "foyer", "direction": "north", "blockedMessage": "The auditorium doors are locked with a heavy chain and padlock." }
    },
    {
      "id": "puzzle-2",
      "scene": "auditorium",
      "requires": ["ghost-light"],
      "action": "Place ghost light in front of backstage door",
      "result": "The ghost light's glow spills through the door's window, illuminating a power panel inside. A relay clicks, and the door's electronic lock disengages.",
      "reveals": ["backstage"],
      "blocksExit": { "scene": "auditorium", "direction": "east", "blockedMessage": "The backstage door is locked. You need light to see the lock mechanism." }
    },
    {
      "id": "puzzle-3",
      "scene": "backstage",
      "requires": ["ghost-light", "makeup-kit"],
      "action": "Combine ghost light with makeup kit at the cracked mirror",
      "result": "The ghost light's reflection in the makeup kit's mirror creates a beam of focused light that illuminates the broken ladder. The missing rungs reappear as shimmering outlines, solid enough to climb.",
      "reveals": ["illuminated-mirror"],
      "blocksExit": { "scene": "backstage", "direction": "up", "blockedMessage": "The ladder's rungs are broken. You can't reach the catwalk." }
    },
    {
      "id": "puzzle-4",
      "scene": "catwalk",
      "requires": ["cue-sheet"],
      "action": "Input symbol sequence on lighting board",
      "result": "The board powers up. Lights snap on across the stage, revealing a previously hidden walkway across the collapsed grid.",
      "reveals": ["stage"],
      "blocksExit": { "scene": "catwalk", "direction": "east", "blockedMessage": "The catwalk grid has collapsed. You can't cross the gap." }
    },
    {
      "id": "puzzle-5",
      "scene": "stage",
      "requires": ["illuminated-mirror", "conductor-baton"],
      "action": "Use illuminated mirror and conductor's baton on the ornate mirror",
      "result": "The mirror shatters with a sound like breaking ice. The curse lifts; the theater breathes again. The ghosts fade, finally at peace.",
      "reveals": [],
      "blocksExit": null
    }
  ],
  "hints": {
    "foyer": [
      { "delay": 30, "text": "That brass key looks like it fits a padlock. Just saying." },
      { "delay": 60, "text": "USE the brass key on the chain. Then go north." },
      { "delay": 90, "text": "Fine. USE key on chain. NORTH. Move." }
    ],
    "auditorium": [
      { "delay": 30, "text": "The ghost light might unlock something. Try the backstage door." },
      { "delay": 60, "text": "USE ghost light on the backstage door east." },
      { "delay": 90, "text": "Point the ghost light at the backstage door. USE it. Then go east." }
    ],
    "backstage": [
      { "delay": 30, "text": "You need both the ghost light AND the makeup kit to fix that ladder. Did you get the makeup kit from the dressing rooms?" },
      { "delay": 60, "text": "Go south to dressing rooms, take makeup kit. Then USE both ghost light and makeup kit on the cracked mirror." },
      { "delay": 90, "text": "Get makeup kit from dressing rooms. USE ghost light and makeup kit on mirror. The catwalk opens up." }
    ],
    "dressing-rooms": [
      { "delay": 30, "text": "That makeup kit is vintage. Take it." },
      { "delay": 60, "text": "Take the makeup kit, go back to backstage." },
      { "delay": 90, "text": "Pick up makeup kit. Now scurry back to backstage." }
    ],
    "catwalk": [
      { "delay": 30, "text": "The cue sheet has a symbol sequence. Use it on the lighting board." },
      { "delay": 60, "text": "USE cue sheet on the lighting board. The stage will be revealed." },
      { "delay": 90, "text": "Apply the cue sheet to the lighting board. East exit opens. Go to stage." }
    ],
    "stage": [
      { "delay": 30, "text": "The illuminated mirror and baton can break the curse. Do you have both?" },
      { "delay": 60, "text": "USE illuminated mirror and conductor's baton on the ornate mirror." },
      { "delay": 90, "text": "Shatter the mirror with both items. Curse breaks. You win." }
    ]
  },
  "winCondition": {
    "scene": "stage",
    "requires": ["illuminated-mirror", "conductor-baton"],
    "description": "Break the curse by using the illuminated mirror and conductor's baton on the ornate mirror upstage."
  }
};

// ---- Game State ----
const state = {
  currentScene: 'foyer',
  inventory: [],
  solvedPuzzles: [],
  visitedScenes: ['foyer'],
  activeCommand: null,
  selectedItem: null,
  won: false,
  hintsEnabled: true,
  hintTimer: null,
  hintIndex: 0
};

// ---- DOM References ----
const artDisplay = document.getElementById('art-display');
const sceneName = document.getElementById('scene-name');
const textDisplay = document.getElementById('text-display');
const invBar = document.getElementById('inventory-bar');
const exitsBar = document.getElementById('exits-bar');

// ---- Display Functions ----
function addText(text, cls = '') {
  const p = document.createElement('p');
  p.className = cls;
  p.innerHTML = text;
  textDisplay.appendChild(p);
  textDisplay.scrollTop = textDisplay.scrollHeight;
}

function clearText() { textDisplay.innerHTML = ''; }

// ---- Locked Exit Check ----
function canExit(sceneId, direction) {
  const scene = GAME_DATA.scenes.find(s => s.id === sceneId);
  if (!scene) return false;
  
  // Check if exit exists in the scene data
  if (!scene.exits[direction]) return false;
  
  // Check if any unsolved puzzle blocks this exit
  const blocker = GAME_DATA.puzzles.find(p =>
    p.blocksExit &&
    p.blocksExit.scene === sceneId &&
    p.blocksExit.direction === direction &&
    !state.solvedPuzzles.includes(p.id)
  );
  
  if (blocker) {
    addText(`[The way ${direction} is blocked. ${blocker.blockedMessage || 'Something prevents you from going that way.'}]`, 'locked');
    return false;
  }
  return true;
}

// ---- Hint System ----
function clearHintTimer() {
  if (state.hintTimer) { clearTimeout(state.hintTimer); state.hintTimer = null; }
  state.hintIndex = 0;
}

function startHintTimer(sceneId) {
  clearHintTimer();
  if (!state.hintsEnabled || !GAME_DATA.hints || !GAME_DATA.hints[sceneId]) return;
  const hints = GAME_DATA.hints[sceneId];
  if (!hints.length) return;
  state.hintTimer = setTimeout(() => showHint(sceneId, 0), hints[0].delay * 1000);
}

function showHint(sceneId, index) {
  if (!state.hintsEnabled || !GAME_DATA.hints || !GAME_DATA.hints[sceneId]) return;
  const hints = GAME_DATA.hints[sceneId];
  if (index >= hints.length) return;
  const hint = hints[index];
  addText(`🤔 HINT: ${hint.text}`, 'hint');
  state.hintIndex = index + 1;
  if (state.hintIndex < hints.length) {
    state.hintTimer = setTimeout(() => showHint(sceneId, state.hintIndex), hints[state.hintIndex].delay * 1000);
  }
}

// ---- Scene Rendering ----
function renderScene(sceneId) {
  const scene = GAME_DATA.scenes.find(s => s.id === sceneId);
  if (!scene) { addText('ERROR: Scene not found!', 'error'); return; }

  clearHintTimer();
  state.currentScene = sceneId;
  if (!state.visitedScenes.includes(sceneId)) state.visitedScenes.push(sceneId);

  // Update scene name
  sceneName.textContent = scene.name.toUpperCase();

  // Update art - check for scene-specific art
  const artKey = 'scene-' + sceneId;
  if (window.GAME_ART && window.GAME_ART[artKey]) {
    artDisplay.innerHTML = window.GAME_ART[artKey];
  } else {
    artDisplay.innerHTML = '<span class="no-art">[ ' + scene.name.toUpperCase() + ' ]</span>';
  }

  // Display prose
  clearText();
  addText(scene.prose);

  // Show available items (not yet taken)
  const availableItems = (scene.items || []).filter(itemId =>
    !state.inventory.includes(itemId)
  );
  if (availableItems.length > 0) {
    const itemNames = availableItems.map(id => {
      const item = GAME_DATA.items.find(i => i.id === id);
      return item ? `<span class="look-target" data-look="${id}" data-type="item">${item.name}</span>` : id;
    });
    addText('You notice: ' + itemNames.join(', '), 'system');
  }

  // Show unsolved puzzles in this scene
  const scenePuzzles = (scene.puzzles || []).filter(pid =>
    !state.solvedPuzzles.includes(pid)
  );
  scenePuzzles.forEach(pid => {
    const puzzle = GAME_DATA.puzzles.find(p => p.id === pid);
    if (puzzle) {
      addText('There is something here that catches your attention...', 'system');
    }
  });

  // Show look targets
  if (scene.lookDescriptions) {
    const targets = Object.keys(scene.lookDescriptions);
    if (targets.length > 0) {
      addText('You can examine: ' + targets.map(t =>
        `<span class="look-target" data-look="${t}" data-type="scene">${t}</span>`
      ).join(', '), 'system');
    }
  }

  // Render exits (respecting locked exits)
  renderExits(scene);

  // Render inventory
  renderInventory();

  // Check win condition
  checkWin();

  // Start hint timer
  startHintTimer(sceneId);

  // Save state
  saveState();
}

function renderExits(scene) {
  exitsBar.innerHTML = '';
  const directions = ['north', 'south', 'east', 'west', 'up', 'down'];
  
  directions.forEach(dir => {
    if (!scene.exits[dir]) return; // No exit in this direction at all
    
    const btn = document.createElement('button');
    btn.className = 'exit-btn';
    btn.textContent = dir.toUpperCase();
    
    // Check if exit is blocked by unsolved puzzle
    const blocker = GAME_DATA.puzzles.find(p =>
      p.blocksExit &&
      p.blocksExit.scene === scene.id &&
      p.blocksExit.direction === dir &&
      !state.solvedPuzzles.includes(p.id)
    );
    
    if (blocker) {
      // Exit exists but is locked
      btn.classList.add('locked');
      btn.title = 'Blocked';
    } else {
      // Exit is available
      btn.classList.add('available');
      btn.onclick = () => go(scene.exits[dir]);
    }
    
    exitsBar.appendChild(btn);
  });
}

function renderInventory() {
  // Remove existing inventory items (keep the label and empty span)
  const items = invBar.querySelectorAll('.inv-item');
  items.forEach(el => el.remove());
  const empty = document.getElementById('inv-empty');
  if (!empty) return;

  if (state.inventory.length === 0) {
    empty.style.display = '';
  } else {
    empty.style.display = 'none';
    state.inventory.forEach(itemId => {
      const item = GAME_DATA.items.find(i => i.id === itemId);
      if (!item) return;
      const el = document.createElement('span');
      el.className = 'inv-item' + (state.selectedItem === itemId ? ' selected' : '');
      el.textContent = item.name;
      el.title = item.description;
      el.onclick = () => selectItem(itemId);
      invBar.appendChild(el);
    });
  }
}

// ---- Command System ----
function setCommand(cmd) {
  state.activeCommand = cmd;
  state.selectedItem = null; // Reset selection on command change
  
  document.querySelectorAll('.cmd-btn').forEach(b => {
    b.classList.toggle('active', b.dataset.cmd === cmd);
  });
  
  if (cmd === 'look') {
    // Refresh the scene to show look targets
    const scene = GAME_DATA.scenes.find(s => s.id === state.currentScene);
    if (scene) renderScene(state.currentScene);
  } else if (cmd === 'take') {
    // Auto-take all available items
    const scene = GAME_DATA.scenes.find(s => s.id === state.currentScene);
    const available = (scene.items || []).filter(id => !state.inventory.includes(id));
    if (available.length > 0) {
      available.forEach(id => takeItem(id));
    } else {
      addText('Nothing here to take.', 'system');
    }
  } else if (cmd === 'use') {
    if (state.inventory.length > 0) {
      addText('Select an item from your inventory, then click what to use it on.', 'system');
    } else {
      addText('You have nothing to use.', 'system');
    }
  } else if (cmd === 'examine') {
    // Show all look targets
    const scene = GAME_DATA.scenes.find(s => s.id === state.currentScene);
    if (scene && scene.lookDescriptions) {
      const targets = Object.keys(scene.lookDescriptions);
      if (targets.length > 0) {
        addText('You can examine: ' + targets.map(t =>
          `<span class="look-target" data-look="${t}" data-type="scene">${t}</span>`
        ).join(', '), 'system');
      }
    }
  }
}

function selectItem(itemId) {
  if (state.activeCommand !== 'use') {
    // Switch to USE mode when clicking inventory item
    setCommand('use');
  }
  state.selectedItem = state.selectedItem === itemId ? null : itemId;
  renderInventory();
  if (state.selectedItem) {
    const item = GAME_DATA.items.find(i => i.id === itemId);
    addText(`Selected: ${item.name}. Now click a target to use it on.`, 'system');
  }
}

function takeItem(itemId) {
  if (state.inventory.includes(itemId)) return;
  const item = GAME_DATA.items.find(i => i.id === itemId);
  if (!item) return;
  const scene = GAME_DATA.scenes.find(s => s.id === state.currentScene);
  if (!scene || !(scene.items || []).includes(itemId)) return;

  state.inventory.push(itemId);
  addText(`You picked up: <strong>${item.name}</strong> \u2014 ${item.description}`, 'success');
  renderInventory();
  saveState();
}

function lookAt(target, targetType) {
  const scene = GAME_DATA.scenes.find(s => s.id === state.currentScene);
  
  if (targetType === 'scene' && scene && scene.lookDescriptions && scene.lookDescriptions[target]) {
    addText(scene.lookDescriptions[target]);
  } else if (targetType === 'item') {
    const item = GAME_DATA.items.find(i => i.id === target);
    if (item) {
      addText(`<strong>${item.name}</strong>: ${item.description}`);
    }
  } else if (targetType === 'scene' || !targetType) {
    // Fallback: check scene look descriptions first
    if (scene && scene.lookDescriptions && scene.lookDescriptions[target]) {
      addText(scene.lookDescriptions[target]);
    } else {
      // Check if it's an item in inventory or scene
      const item = GAME_DATA.items.find(i => i.id === target);
      if (item) {
        addText(`<strong>${item.name}</strong>: ${item.description}`);
      } else {
        addText(`You see nothing special about "${target}".`, 'system');
      }
    }
  }
}

// ---- Puzzle Solving ----
function trySolvePuzzle(itemId, targetId) {
  // Find a puzzle that:
  // 1. Is in the current scene
  // 2. Requires the given item
  // 3. Hasn't been solved yet
  
  const puzzle = GAME_DATA.puzzles.find(p =>
    p.scene === state.currentScene &&
    !state.solvedPuzzles.includes(p.id) &&
    p.requires.includes(itemId)
  );
  
  if (!puzzle) {
    return false;
  }
  
  // Check if player has ALL required items
  const hasAll = puzzle.requires.every(req => state.inventory.includes(req));
  if (!hasAll) {
    const missing = puzzle.requires.filter(req => !state.inventory.includes(req));
    const missingNames = missing.map(id => {
      const item = GAME_DATA.items.find(i => i.id === id);
      return item ? item.name : id;
    });
    addText(`You need: ${missingNames.join(', ')} to do that.`, 'system');
    return false;
  }
  
  // SOLVE THE PUZZLE!
  state.solvedPuzzles.push(puzzle.id);
  addText(puzzle.result, 'success');
  
  // Visual feedback - flash effect
  if (artDisplay) {
    artDisplay.classList.add('puzzle-solved');
    setTimeout(() => artDisplay.classList.remove('puzzle-solved'), 600);
  }
  
  // Remove used items from inventory (they're consumed)
  puzzle.requires.forEach(reqId => {
    const idx = state.inventory.indexOf(reqId);
    if (idx !== -1) state.inventory.splice(idx, 1);
  });
  
  // Reveal any new items
  (puzzle.reveals || []).forEach(revealId => {
    const revealItem = GAME_DATA.items.find(i => i.id === revealId);
    if (revealItem && revealItem.foundIn === null) {
      // Item is created/added to inventory directly (like illuminated-mirror)
      state.inventory.push(revealId);
      addText(`You now have: <strong>${revealItem.name}</strong>!`, 'success');
    }
  });
  
  // Re-render scene to show updated exits
  renderScene(state.currentScene);
  addText('[NEW EXIT UNLOCKED]', 'success');
  
  saveState();
  return true;
}

function useItemOn(itemId, targetId) {
  // Try to solve a puzzle with this item combination
  const solved = trySolvePuzzle(itemId, targetId);
  
  if (!solved) {
    // Check if it's just a wrong combination
    const item = GAME_DATA.items.find(i => i.id === itemId);
    addText(`Using ${item ? item.name : 'that'} doesn't seem to work here.`, 'system');
  }
}

// ---- Navigation ----
function go(sceneId) {
  if (state.won) {
    addText('The curse is broken. The theater is at peace.', 'system');
    return;
  }
  
  // Determine direction from current scene to target
  const currentScene = GAME_DATA.scenes.find(s => s.id === state.currentScene);
  if (!currentScene) return;
  
  let direction = null;
  for (const [dir, target] of Object.entries(currentScene.exits)) {
    if (target === sceneId) {
      direction = dir;
      break;
    }
  }
  
  // Check if exit is locked
  if (direction && !canExit(state.currentScene, direction)) {
    return; // canExit already displayed the blocked message
  }
  
  addText('---', 'system');
  renderScene(sceneId);
}

// ---- Win Condition ----
function checkWin() {
  if (state.won) return;
  const wc = GAME_DATA.winCondition;
  if (!wc) return;
  
  if (state.currentScene === wc.scene &&
      wc.requires.every(req => state.inventory.includes(req))) {
    state.won = true;
    addText('', '');
    addText('=== YOU HAVE WON! ===', 'success');
    addText(wc.description, 'success');
    addText('', '');
    addText('The mirror shatters. Light floods the theater. The frozen audience stirs\u2014gasping, murmuring, alive. Eleanor Vance steps from the broken mirror, tears streaming. The Stage Manager checks his watch one final time and nods. The show is finally over.', 'success');
    addText('', '');
    addText('CONGRATULATIONS! YOU HAVE COMPLETED CURTAIN CALL!', 'success');
    addText('Refresh the page to play again.', 'system');
    
    // Victory flash
    if (artDisplay) {
      artDisplay.classList.add('puzzle-solved');
      setTimeout(() => artDisplay.classList.remove('puzzle-solved'), 600);
    }
  }
}

// ---- Persistence ----
function saveState() {
  try {
    localStorage.setItem('game-' + GAME_DATA.slug, JSON.stringify(state));
  } catch(e) { /* localStorage not available */ }
}

function loadState() {
  try {
    const saved = localStorage.getItem('game-' + GAME_DATA.slug);
    if (saved) {
      const s = JSON.parse(saved);
      Object.assign(state, s);
      return true;
    }
  } catch(e) { /* no saved state */ }
  return false;
}

// ---- Event Listeners ----
document.querySelectorAll('.cmd-btn').forEach(btn => {
  btn.onclick = () => setCommand(btn.dataset.cmd);
});

document.addEventListener('click', (e) => {
  const target = e.target;
  
  if (target.classList.contains('look-target')) {
    const lookTarget = target.dataset.look;
    const targetType = target.dataset.type;
    
    if (state.activeCommand === 'use' && state.selectedItem) {
      // USE selected item ON this target
      useItemOn(state.selectedItem, lookTarget);
    } else {
      // Default: look/examine
      lookAt(lookTarget, targetType);
    }
  }
});

// ---- Initialize ----
function init() {
  // Add CSS for puzzle-solved animation
  const style = document.createElement('style');
  style.textContent = `
    .puzzle-solved { animation: solveFlash 0.6s ease; }
    @keyframes solveFlash { 0%,100%{filter:none} 50%{filter:brightness(2) saturate(2)} }
    .exit-btn.newly-unlocked { animation: unlockPulse 1s ease 3; }
    @keyframes unlockPulse { 0%,100%{border-color:#33ff33} 50%{border-color:#ffff33;box-shadow:0 0 12px #ffff33} }
    .item-new { animation: itemGlow 1s ease 2; }
    @keyframes itemGlow { 0%,100%{background:transparent} 50%{background:rgba(51,255,51,0.3)} }
    .exit-btn.locked { border-color: #663333; color: #663333; cursor: not-allowed; }
  `;
  document.head.appendChild(style);

  addText('=== CURTAIN CALL ===', 'success');
  addText(GAME_DATA.setting, 'system');
  addText('', '');
  addText('Commands: LOOK | TAKE | USE | EXAMINE', 'system');
  addText('Click exits to move between rooms. Click inventory items to select them.', 'system');
  addText('---', 'system');

  if (!loadState()) {
    renderScene('foyer');
  } else {
    renderScene(state.currentScene);
    addText('[Game restored from save]', 'system');
  }

  // Hint toggle button
  const hintToggle = document.getElementById('hint-toggle');
  if (hintToggle) {
    hintToggle.textContent = state.hintsEnabled ? 'HINTS: ON' : 'HINTS: OFF';
    hintToggle.addEventListener('click', () => {
      state.hintsEnabled = !state.hintsEnabled;
      hintToggle.textContent = state.hintsEnabled ? 'HINTS: ON' : 'HINTS: OFF';
      if (!state.hintsEnabled) clearHintTimer();
      else startHintTimer(state.currentScene);
      saveState();
    });
  }
}

// Start the game
init();
